/* Copyright (C) 2016 MINHAP, Gobierno de España
   This program is licensed and may be used, modified and redistributed under the terms
   of the European Public License (EUPL), either version 1.1 or (at your
   option) any later version as soon as they are approved by the European Commission.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
   or implied. See the License for the specific language governing permissions and
   more details.
   You should have received a copy of the EUPL1.1 license
   along with this program; if not, you may find it at
   http://joinup.ec.europa.eu/software/page/eupl/licence-eupl */

package es.mpt.dsic.inside.store.hibernate.entity;

// Generated 28-ago-2012 18:17:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.TableGenerator;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExpedienteInsideIndiceFirmas generated by hbm2java
 */
@Entity
@Table(name = "ExpedienteInsideIndiceFirmas")
public class ExpedienteInsideIndiceFirmas implements java.io.Serializable {

	private Integer id;
	private FirmaInside firmaInside;
	private ExpedienteInside expedienteInside;

	public ExpedienteInsideIndiceFirmas() {
	}

	public ExpedienteInsideIndiceFirmas(FirmaInside firmaInside,
			ExpedienteInside expedienteInside) {
		this.firmaInside = firmaInside;
		this.expedienteInside = expedienteInside;
	}

	@Id
	//@GeneratedValue(strategy = IDENTITY)
	@TableGenerator(name = "GeneradorPk_ExpedienteInsideIndiceFirmas",
    		table = "GeneradorClaves",
    		pkColumnName = "GenName",
    		valueColumnName = "GenValue",
    		pkColumnValue = "GEN_ExpedienteInsideIndiceFirmas",
    		allocationSize=1)
    @GeneratedValue(strategy = GenerationType.TABLE, generator = "GeneradorPk_ExpedienteInsideIndiceFirmas")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_firmaInside", nullable = false)
	public FirmaInside getFirmaInside() {
		return this.firmaInside;
	}

	public void setFirmaInside(FirmaInside firmaInside) {
		this.firmaInside = firmaInside;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_expediente", nullable = false)
	public ExpedienteInside getExpedienteInside() {
		return this.expedienteInside;
	}

	public void setExpedienteInside(ExpedienteInside expedienteInside) {
		this.expedienteInside = expedienteInside;
	}
	
	public String toString () {
		StringBuffer sb = new StringBuffer ("Entity ExpedienteInsideIndiceFirmas=[");
		String coma = ", ";
		
		sb.append ("id=" + id + coma);
		if (firmaInside == null) {
			sb.append("firmaInside=null");
		}else {
			sb.append("firmaInside=" + firmaInside.toString());
		}
		
		sb.append("]");
		return sb.toString();
	}

}
