<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="EeUtilFirmarServiceImplService" targetNamespace="http://impl.service.ws.inside.dsic.mpt.es/" xmlns:ns1="http://service.ws.inside.dsic.mpt.es/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://impl.service.ws.inside.dsic.mpt.es/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="EeUtilFirmarService_types" namespace="http://service.ws.inside.dsic.mpt.es/">
    </wsdl:import>
  <wsdl:binding name="EeUtilFirmarServiceImplServiceSoapBinding" type="ns1:EeUtilFirmarService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="firmaFichero">
      <soap:operation soapAction="urn:FirmaFichero" style="document"/>
      <wsdl:input name="firmaFichero">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="firmaFicheroResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="EeUtilFirmarServiceImplService">
    <wsdl:port binding="tns:EeUtilFirmarServiceImplServiceSoapBinding" name="EeUtilFirmarServiceImplPort">
      <soap:address location="http://server:port/eeutil/ws/EeUtilFirmarService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
