/*
 * Copyright (C) 2016 MINHAP, Gobierno de España This program is licensed and may be used, modified
 * and redistributed under the terms of the European Public License (EUPL), either version 1.1 or
 * (at your option) any later version as soon as they are approved by the European Commission.
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package es.mpt.dsic.inside.service.validacionENIMtom.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3 2016-11-02T08:45:03.603+01:00 Generated source
 * version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
    name = "EeUtilValidacionENIServiceMtom")
@XmlSeeAlso({ObjectFactory.class})
public interface EeUtilValidacionENIServiceMtom {

  @WebResult(name = "Resultado", targetNamespace = "")
  @RequestWrapper(localName = "validarFirmaExpedienteENI",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.inside.service.validacionENIMtom.model.ValidarFirmaExpedienteENI")
  @WebMethod(action = "urn:validarFirmaExpedienteENI")
  @ResponseWrapper(localName = "validarFirmaExpedienteENIResponse",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.inside.service.validacionENIMtom.model.ValidarFirmaExpedienteENIResponse")
  public es.mpt.dsic.inside.service.validacionENIMtom.model.RespuestaValidacionENI validarFirmaExpedienteENI(
      @WebParam(name = "aplicacionInfo",
          targetNamespace = "") es.mpt.dsic.inside.service.validacionENIMtom.model.ApplicationLogin aplicacionInfo,
      @WebParam(name = "DocumentoEntradaMtom",
          targetNamespace = "") es.mpt.dsic.inside.service.validacionENIMtom.model.DocumentoEntradaMtom documentoEntradaMtom);

  @WebResult(name = "Resultado", targetNamespace = "")
  @RequestWrapper(localName = "validarExpedienteENI",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.inside.service.validacionENIMtom.model.ValidarExpedienteENI")
  @WebMethod(action = "urn:validarExpedienteENI")
  @ResponseWrapper(localName = "validarExpedienteENIResponse",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.inside.service.validacionENIMtom.model.ValidarExpedienteENIResponse")
  public es.mpt.dsic.inside.service.validacionENIMtom.model.RespuestaValidacionENI validarExpedienteENI(
      @WebParam(name = "aplicacionInfo",
          targetNamespace = "") es.mpt.dsic.inside.service.validacionENIMtom.model.ApplicationLogin aplicacionInfo,
      @WebParam(name = "DocumentoEntradaMtom",
          targetNamespace = "") es.mpt.dsic.inside.service.validacionENIMtom.model.DocumentoEntradaMtom documentoEntradaMtom,
      @WebParam(name = "versionENI", targetNamespace = "") java.lang.String versionENI,
      @WebParam(name = "validaciones",
          targetNamespace = "") es.mpt.dsic.inside.service.validacionENIMtom.model.Validaciones validaciones);

  @WebResult(name = "Resultado", targetNamespace = "")
  @RequestWrapper(localName = "validarDocumentoENI",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.inside.service.validacionENIMtom.model.ValidarDocumentoENI")
  @WebMethod(action = "urn:validarDocumentoENI")
  @ResponseWrapper(localName = "validarDocumentoENIResponse",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.inside.service.validacionENIMtom.model.ValidarDocumentoENIResponse")
  public es.mpt.dsic.inside.service.validacionENIMtom.model.RespuestaValidacionENI validarDocumentoENI(
      @WebParam(name = "aplicacionInfo",
          targetNamespace = "") es.mpt.dsic.inside.service.validacionENIMtom.model.ApplicationLogin aplicacionInfo,
      @WebParam(name = "DocumentoEntradaMtom",
          targetNamespace = "") es.mpt.dsic.inside.service.validacionENIMtom.model.DocumentoEntradaMtom documentoEntradaMtom,
      @WebParam(name = "versionENI", targetNamespace = "") java.lang.String versionENI,
      @WebParam(name = "validaciones",
          targetNamespace = "") es.mpt.dsic.inside.service.validacionENIMtom.model.Validaciones validaciones);

  @WebResult(name = "Resultado", targetNamespace = "")
  @RequestWrapper(localName = "validarFirmaDocumentoENI",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.inside.service.validacionENIMtom.model.ValidarFirmaDocumentoENI")
  @WebMethod(action = "urn:validarFirmaDocumentoENI")
  @ResponseWrapper(localName = "validarFirmaDocumentoENIResponse",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.inside.service.validacionENIMtom.model.ValidarFirmaDocumentoENIResponse")
  public es.mpt.dsic.inside.service.validacionENIMtom.model.RespuestaValidacionENI validarFirmaDocumentoENI(
      @WebParam(name = "aplicacionInfo",
          targetNamespace = "") es.mpt.dsic.inside.service.validacionENIMtom.model.ApplicationLogin aplicacionInfo,
      @WebParam(name = "DocumentoEntradaMtom",
          targetNamespace = "") es.mpt.dsic.inside.service.validacionENIMtom.model.DocumentoEntradaMtom documentoEntradaMtom);
}
