/*
 * Copyright (C) 2016 MINHAP, Gobierno de España This program is licensed and may be used, modified
 * and redistributed under the terms of the European Public License (EUPL), either version 1.1 or
 * (at your option) any later version as soon as they are approved by the European Commission.
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package es.mpt.dsic.inside.service.sia.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1 2014-06-23T17:22:05.937+02:00 Generated source
 * version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.map.es/sgca/consultar",
    name = "wsSIAConsultarActuacionesIdentificacion")
@XmlSeeAlso({es.mpt.dsic.inside.service.sia.model.messages.v2_4.enviasia.ObjectFactory.class,
    es.mpt.dsic.inside.service.sia.model.messages.enviasia.ObjectFactory.class,
    es.mpt.dsic.inside.service.sia.model.messages.paramsia.ObjectFactory.class,
    es.mpt.dsic.inside.service.sia.model.messages.v2_4.paramsia.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WsSIAConsultarActuacionesIdentificacion {

  @WebResult(name = "enviaSIA",
      targetNamespace = "http://www.map.es/sgca/consultar/messages/v2_4/EnviaSIA",
      partName = "parameters")
  @WebMethod(operationName = "consultarSIA_v2_4",
      action = "http://www.map.es/sgca/consultar/consultarSIA_v2_4")
  public es.mpt.dsic.inside.service.sia.model.messages.v2_4.enviasia.EnviaSIA consultarSIAV24(
      @WebParam(partName = "parameters", name = "paramSIA",
          targetNamespace = "http://www.map.es/sgca/consultar/messages/v2_4/ParamSIA") es.mpt.dsic.inside.service.sia.model.messages.v2_4.paramsia.ParamSIA parameters);

  @WebResult(name = "enviaSIA",
      targetNamespace = "http://www.map.es/sgca/consultar/messages/EnviaSIA",
      partName = "parameters")
  @WebMethod(action = "http://www.map.es/sgca/consultar/consultarSIA")
  public es.mpt.dsic.inside.service.sia.model.messages.enviasia.EnviaSIA consultarSIA(@WebParam(
      partName = "parameters", name = "paramSIA",
      targetNamespace = "http://www.map.es/sgca/consultar/messages/ParamSIA") es.mpt.dsic.inside.service.sia.model.messages.paramsia.ParamSIA parameters);
}

