/*
 * Copyright (C) 2016 MINHAP, Gobierno de España This program is licensed and may be used, modified
 * and redistributed under the terms of the European Public License (EUPL), either version 1.1 or
 * (at your option) any later version as soon as they are approved by the European Commission.
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */


package es.mpt.dsic.inside.remisionnube.client.modelo;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3 2016-12-13T12:56:42.363+01:00 Generated source
 * version: 3.0.3
 */

@WebFault(name = "errorInside",
    targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService/types/error")
public class InsideWSException extends Exception {

  private es.mpt.dsic.inside.remisionnube.client.modelo.WSErrorInside errorInside;

  public InsideWSException() {
    super();
  }

  public InsideWSException(String message) {
    super(message);
  }

  public InsideWSException(String message, Throwable cause) {
    super(message, cause);
  }

  public InsideWSException(String message,
      es.mpt.dsic.inside.remisionnube.client.modelo.WSErrorInside errorInside) {
    super(message);
    this.errorInside = errorInside;
  }

  public InsideWSException(String message,
      es.mpt.dsic.inside.remisionnube.client.modelo.WSErrorInside errorInside, Throwable cause) {
    super(message, cause);
    this.errorInside = errorInside;
  }

  public es.mpt.dsic.inside.remisionnube.client.modelo.WSErrorInside getFaultInfo() {
    return this.errorInside;
  }
}
