/*
 * Copyright (C) 2016 MINHAP, Gobierno de España This program is licensed and may be used, modified
 * and redistributed under the terms of the European Public License (EUPL), either version 1.1 or
 * (at your option) any later version as soon as they are approved by the European Commission.
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package es.mpt.dsic.inside.remisionnube.client.modelo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3 2016-10-13T09:54:54.860+02:00 Generated source
 * version: 3.0.3
 * 
 */
@WebService(targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
    name = "InsideRemisionNubeExpedientesService")
@XmlSeeAlso({ObjectFactory.class})
public interface InsideRemisionNubeExpedientesService {

  @WebResult(name = "RespuestaAccesoDocumentoExpedienteType", targetNamespace = "")
  @RequestWrapper(localName = "accesoDocumentoExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AccesoDocumentoExpediente")
  @WebMethod(action = "urn:accesoDocumentoExpediente")
  @ResponseWrapper(localName = "accesoDocumentoExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AccesoDocumentoExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.RespuestaAccesoDocumentoExpedienteType accesoDocumentoExpediente(
      @WebParam(name = "peticionAccesoDocumentoExpedienteType",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.PeticionAccesoDocumentoExpedienteType peticionAccesoDocumentoExpedienteType)
      throws InsideWSException;

  @WebResult(name = "RespuestaAccesoIndiceExpedienteType", targetNamespace = "")
  @RequestWrapper(localName = "accesoIndiceExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AccesoIndiceExpediente")
  @WebMethod(action = "urn:accesoIndiceExpediente")
  @ResponseWrapper(localName = "accesoIndiceExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AccesoIndiceExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.RespuestaAccesoIndiceExpedienteType accesoIndiceExpediente(
      @WebParam(name = "peticionAccesoIndiceExpedienteType",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.PeticionAccesoIndiceExpedienteType peticionAccesoIndiceExpedienteType)
      throws InsideWSException;
}
