/*
 * Copyright (C) 2016 MINHAP, Gobierno de España This program is licensed and may be used, modified
 * and redistributed under the terms of the European Public License (EUPL), either version 1.1 or
 * (at your option) any later version as soon as they are approved by the European Commission.
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package es.mpt.dsic.inside.remisionnube.client.modelo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3 2016-09-23T10:44:32.394+02:00 Generated source
 * version: 3.0.3
 * 
 */
@WebService(targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
    name = "InSideUserTokenWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface InSideUserTokenWebService {

  @WebResult(name = "documento", targetNamespace = "")
  @RequestWrapper(localName = "getDocumentoContenido",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetDocumentoContenido")
  @WebMethod(action = "urn:getDocumentoContenido")
  @ResponseWrapper(localName = "getDocumentoContenidoResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetDocumentoContenidoResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.TipoContenido getDocumentoContenido(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador,
      @WebParam(name = "version", targetNamespace = "") java.lang.Integer version)
      throws InsideWSException;

  @WebResult(name = "ExpedienteInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "vincularExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.VincularExpediente")
  @WebMethod(action = "urn:vincularExpediente")
  @ResponseWrapper(localName = "vincularExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.VincularExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteInsideInfo vincularExpediente(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador,
      @WebParam(name = "identificadorVinculado",
          targetNamespace = "") java.lang.String identificadorVinculado,
      @WebParam(name = "ruta", targetNamespace = "") java.lang.String ruta)
      throws InsideWSException;

  @WebResult(name = "ExpedienteInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "altaExpedienteEniXml",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaExpedienteEniXml")
  @WebMethod(action = "urn:altaExpedienteEniXml")
  @ResponseWrapper(localName = "altaExpedienteEniXmlResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaExpedienteEniXmlResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteInsideInfo altaExpedienteEniXml(
      @WebParam(name = "expedienteEniFile",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoExpedienteEniFileInsideConDocumentos expedienteEniFile)
      throws InsideWSException;

  @WebResult(name = "metadatos", targetNamespace = "")
  @RequestWrapper(localName = "getMetadatosDocumento",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetMetadatosDocumento")
  @WebMethod(action = "urn:getMetadatosDocumento")
  @ResponseWrapper(localName = "getMetadatosDocumentoResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetMetadatosDocumentoResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.DocumentoInsideMetadatos getMetadatosDocumento(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador,
      @WebParam(name = "version", targetNamespace = "") java.lang.Integer version)
      throws InsideWSException;

  @WebResult(name = "ExpedienteInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "cambiaMetadatosExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.CambiaMetadatosExpediente")
  @WebMethod(action = "urn:cambiaMetadatosExpediente")
  @ResponseWrapper(localName = "cambiaMetadatosExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.CambiaMetadatosExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteInsideInfo cambiaMetadatosExpediente(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador,
      @WebParam(name = "metadatosEni",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoMetadatos metadatosEni,
      @WebParam(name = "metadatosAdicionales",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoMetadatosAdicionales metadatosAdicionales)
      throws InsideWSException;

  @WebResult(name = "ExpedienteInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "importarExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.ImportarExpediente")
  @WebMethod(action = "urn:importarExpediente")
  @ResponseWrapper(localName = "importarExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.ImportarExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteInsideInfo importarExpediente(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador,
      @WebParam(name = "identificadorImportado",
          targetNamespace = "") java.lang.String identificadorImportado,
      @WebParam(name = "ruta", targetNamespace = "") java.lang.String ruta)
      throws InsideWSException;

  @WebResult(name = "DocumentoInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "altaDocumentoEni",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaDocumentoEni")
  @WebMethod(action = "urn:altaDocumentoEni")
  @ResponseWrapper(localName = "altaDocumentoEniResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaDocumentoEniResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.DocumentoInsideInfo altaDocumentoEni(
      @WebParam(name = "documento",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoDocumento documento,
      @WebParam(name = "asociadoaExpediente",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoDocumentoAsociadoaExpediente asociadoaExpediente,
      @WebParam(name = "metadatosAdicionales",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoMetadatosAdicionales metadatosAdicionales,
      @WebParam(name = "firmaServidor", targetNamespace = "") boolean firmaServidor)
      throws InsideWSException;

  @WebResult(name = "resultadoVisualizacion", targetNamespace = "")
  @RequestWrapper(localName = "visualizarDocumento",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.VisualizarDocumento")
  @WebMethod(action = "urn:visualizarDocumento")
  @ResponseWrapper(localName = "visualizarDocumentoResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.VisualizarDocumentoResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.TipoResultadoVisualizacionDocumentoInside visualizarDocumento(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador)
      throws InsideWSException;

  @WebResult(name = "ExpedienteInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "altaCarpetaEnExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaCarpetaEnExpediente")
  @WebMethod(action = "urn:altaCarpetaEnExpediente")
  @ResponseWrapper(localName = "altaCarpetaEnExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaCarpetaEnExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteInsideInfo altaCarpetaEnExpediente(
      @WebParam(name = "identificadorExpediente",
          targetNamespace = "") java.lang.String identificadorExpediente,
      @WebParam(name = "carpetaIndizada",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoCarpetaIndizada carpetaIndizada,
      @WebParam(name = "ruta", targetNamespace = "") java.lang.String ruta)
      throws InsideWSException;

  @WebResult(name = "documentoEniFile", targetNamespace = "")
  @RequestWrapper(localName = "getDocumentoEniFile",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetDocumentoEniFile")
  @WebMethod(action = "urn:getDocumentoEniFile")
  @ResponseWrapper(localName = "getDocumentoEniFileResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetDocumentoEniFileResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.TipoDocumentoEniFileInside getDocumentoEniFile(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador)
      throws InsideWSException;

  @WebResult(name = "documento", targetNamespace = "")
  @RequestWrapper(localName = "convertirDocumentoAEni",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.ConvertirDocumentoAEni")
  @WebMethod(action = "urn:convertirDocumentoAEni")
  @ResponseWrapper(localName = "convertirDocumentoAEniResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.ConvertirDocumentoAEniResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.TipoDocumento convertirDocumentoAEni(
      @WebParam(name = "documento",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoDocumentoConversionInside documento,
      @WebParam(name = "contenido", targetNamespace = "") byte[] contenido)
      throws InsideWSException;

  @WebResult(name = "DocumentoInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "altaDocumentoOriginal",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaDocumentoOriginal")
  @WebMethod(action = "urn:altaDocumentoOriginal")
  @ResponseWrapper(localName = "altaDocumentoOriginalResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaDocumentoOriginalResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.DocumentoInsideInfo altaDocumentoOriginal(
      @WebParam(name = "documento",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoDocumentoAltaInside documento)
      throws InsideWSException;

  @WebResult(name = "metadatos", targetNamespace = "")
  @RequestWrapper(localName = "getExpedienteMetadatos",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetExpedienteMetadatos")
  @WebMethod(action = "urn:getExpedienteMetadatos")
  @ResponseWrapper(localName = "getExpedienteMetadatosResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetExpedienteMetadatosResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteInsideMetadatos getExpedienteMetadatos(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador,
      @WebParam(name = "version", targetNamespace = "") java.lang.Integer version)
      throws InsideWSException;

  @WebResult(name = "versiones", targetNamespace = "")
  @RequestWrapper(localName = "getVersionesExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetVersionesExpediente")
  @WebMethod(action = "urn:getVersionesExpediente")
  @ResponseWrapper(localName = "getVersionesExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetVersionesExpedienteResponse")
  public java.util.List<es.mpt.dsic.inside.remisionnube.client.modelo.TipoVersionInside> getVersionesExpediente(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador)
      throws InsideWSException;

  @WebResult(name = "ExpedienteInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "crearVistaAbiertaExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.CrearVistaAbiertaExpediente")
  @WebMethod(action = "urn:crearVistaAbiertaExpediente")
  @ResponseWrapper(localName = "crearVistaAbiertaExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.CrearVistaAbiertaExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteInsideInfo crearVistaAbiertaExpediente(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador)
      throws InsideWSException;

  @WebResult(name = "DocumentoInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "altaDocumentoCambioFormato",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaDocumentoCambioFormato")
  @WebMethod(action = "urn:altaDocumentoCambioFormato")
  @ResponseWrapper(localName = "altaDocumentoCambioFormatoResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaDocumentoCambioFormatoResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.DocumentoInsideInfo altaDocumentoCambioFormato(
      @WebParam(name = "documento",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoDocumentoAltaInside documento,
      @WebParam(name = "identificadorDocumentoOrigen",
          targetNamespace = "") java.lang.String identificadorDocumentoOrigen)
      throws InsideWSException;

  @RequestWrapper(localName = "eliminarDocumento",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.EliminarDocumento")
  @WebMethod(action = "urn:eliminarDocumento")
  @ResponseWrapper(localName = "eliminarDocumentoResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.EliminarDocumentoResponse")
  public void eliminarDocumento(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador)
      throws InsideWSException;

  @WebResult(name = "DocumentoInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "modificaDocumento",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.ModificaDocumento")
  @WebMethod(action = "urn:modificaDocumento")
  @ResponseWrapper(localName = "modificaDocumentoResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.ModificaDocumentoResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.DocumentoInsideInfo modificaDocumento(
      @WebParam(name = "documento",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoDocumento documento,
      @WebParam(name = "metadatosAdicionales",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoMetadatosAdicionales metadatosAdicionales)
      throws InsideWSException;

  @WebResult(name = "DocumentoInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "altaDocumentoDigitalizado",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaDocumentoDigitalizado")
  @WebMethod(action = "urn:altaDocumentoDigitalizado")
  @ResponseWrapper(localName = "altaDocumentoDigitalizadoResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaDocumentoDigitalizadoResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.DocumentoInsideInfo altaDocumentoDigitalizado(
      @WebParam(name = "documento",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoDocumentoAltaInside documento)
      throws InsideWSException;

  @WebResult(name = "ExpedienteInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "borrarCarpetaEnExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.BorrarCarpetaEnExpediente")
  @WebMethod(action = "urn:borrarCarpetaEnExpediente")
  @ResponseWrapper(localName = "borrarCarpetaEnExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.BorrarCarpetaEnExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteInsideInfo borrarCarpetaEnExpediente(
      @WebParam(name = "identificadorExpediente",
          targetNamespace = "") java.lang.String identificadorExpediente,
      @WebParam(name = "identificadorCarpeta",
          targetNamespace = "") java.lang.String identificadorCarpeta,
      @WebParam(name = "ruta", targetNamespace = "") java.lang.String ruta)
      throws InsideWSException;

  @WebResult(name = "expediente", targetNamespace = "")
  @RequestWrapper(localName = "expedientesAsociadoDocumento",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.ExpedientesAsociadoDocumento")
  @WebMethod(action = "urn:expedientesAsociadoDocumento")
  @ResponseWrapper(localName = "expedientesAsociadoDocumentoResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.ExpedientesAsociadoDocumentoResponse")
  public java.util.List<es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteInsideInfo> expedientesAsociadoDocumento(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador)
      throws InsideWSException;

  @WebResult(name = "DocumentoInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "cambiaMetadatosDocumento",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.CambiaMetadatosDocumento")
  @WebMethod(action = "urn:cambiaMetadatosDocumento")
  @ResponseWrapper(localName = "cambiaMetadatosDocumentoResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.CambiaMetadatosDocumentoResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.DocumentoInsideInfo cambiaMetadatosDocumento(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador,
      @WebParam(name = "metadatosEni",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoMetadatos2 metadatosEni,
      @WebParam(name = "metadatosAdicionales",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoMetadatosAdicionales metadatosAdicionales)
      throws InsideWSException;

  @WebResult(name = "RespuestaSolicitarAccesoExpedienteType", targetNamespace = "")
  @RequestWrapper(localName = "solicitarAccesoExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.SolicitarAccesoExpediente")
  @WebMethod(action = "urn:solicitarAccesoExpediente")
  @ResponseWrapper(localName = "solicitarAccesoExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.SolicitarAccesoExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.RespuestaSolicitarAccesoExpedienteType solicitarAccesoExpediente(
      @WebParam(name = "peticionSolicitarAccesoExpedienteType",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.PeticionSolicitarAccesoExpedienteType peticionSolicitarAccesoExpedienteType)
      throws InsideWSException;

  @WebResult(name = "ExpedienteInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "cambiarUbicacionEnExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.CambiarUbicacionEnExpediente")
  @WebMethod(action = "urn:cambiarUbicacionEnExpediente")
  @ResponseWrapper(localName = "cambiarUbicacionEnExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.CambiarUbicacionEnExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteInsideInfo cambiarUbicacionEnExpediente(
      @WebParam(name = "identificadorExpediente",
          targetNamespace = "") java.lang.String identificadorExpediente,
      @WebParam(name = "identificadoresElementos",
          targetNamespace = "") java.util.List<java.lang.String> identificadoresElementos,
      @WebParam(name = "rutaOrigen", targetNamespace = "") java.lang.String rutaOrigen,
      @WebParam(name = "rutaDestino", targetNamespace = "") java.lang.String rutaDestino)
      throws InsideWSException;

  @WebResult(name = "DocumentoInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "altaDocumentoCopiaParcial",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaDocumentoCopiaParcial")
  @WebMethod(action = "urn:altaDocumentoCopiaParcial")
  @ResponseWrapper(localName = "altaDocumentoCopiaParcialResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaDocumentoCopiaParcialResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.DocumentoInsideInfo altaDocumentoCopiaParcial(
      @WebParam(name = "documento",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoDocumentoAltaInside documento,
      @WebParam(name = "identificadorDocumentoOrigen",
          targetNamespace = "") java.lang.String identificadorDocumentoOrigen)
      throws InsideWSException;

  @WebResult(name = "expediente", targetNamespace = "")
  @RequestWrapper(localName = "convertirExpedienteAEni",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.ConvertirExpedienteAEni")
  @WebMethod(action = "urn:convertirExpedienteAEni")
  @ResponseWrapper(localName = "convertirExpedienteAEniResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.ConvertirExpedienteAEniResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.TipoExpediente convertirExpedienteAEni(
      @WebParam(name = "expediente",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoExpedienteConversionInside expediente)
      throws InsideWSException;

  @WebResult(name = "documento", targetNamespace = "")
  @RequestWrapper(localName = "getDocumento",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetDocumento")
  @WebMethod(action = "urn:getDocumento")
  @ResponseWrapper(localName = "getDocumentoResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetDocumentoResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.TipoDocumentoInside getDocumento(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador,
      @WebParam(name = "version", targetNamespace = "") java.lang.Integer version)
      throws InsideWSException;

  @WebResult(name = "documento", targetNamespace = "")
  @RequestWrapper(localName = "getDocumentoEni",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetDocumentoEni")
  @WebMethod(action = "urn:getDocumentoEni")
  @ResponseWrapper(localName = "getDocumentoEniResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetDocumentoEniResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.TipoDocumento getDocumentoEni(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador)
      throws InsideWSException;

  @WebResult(name = "expediente", targetNamespace = "")
  @RequestWrapper(localName = "getExpedienteEni",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetExpedienteEni")
  @WebMethod(action = "urn:getExpedienteEni")
  @ResponseWrapper(localName = "getExpedienteEniResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetExpedienteEniResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.TipoExpediente getExpedienteEni(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador)
      throws InsideWSException;

  @WebResult(name = "RespuestaRemisionAJusticiaType", targetNamespace = "")
  @RequestWrapper(localName = "remisionAJusticia",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.RemisionAJusticia")
  @WebMethod(action = "urn:remisionAJusticia")
  @ResponseWrapper(localName = "remisionAJusticiaResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.RemisionAJusticiaResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.RespuestaRemisionAJusticiaType remisionAJusticia(
      @WebParam(name = "peticionRemisionAJusticiaType",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.PeticionRemisionAJusticiaType peticionRemisionAJusticiaType)
      throws InsideWSException;

  @WebResult(name = "DocumentoInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "altaDocumentoOtros",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaDocumentoOtros")
  @WebMethod(action = "urn:altaDocumentoOtros")
  @ResponseWrapper(localName = "altaDocumentoOtrosResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaDocumentoOtrosResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.DocumentoInsideInfo altaDocumentoOtros(
      @WebParam(name = "documento",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoDocumentoAltaInside documento)
      throws InsideWSException;

  @WebResult(name = "RespuestaComunicacionResultadoEnvioMJUType", targetNamespace = "")
  @RequestWrapper(localName = "informarRemisionMJU",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.InformarRemisionMJU")
  @WebMethod(action = "urn:informarRemisionMJU")
  @ResponseWrapper(localName = "informarRemisionMJUResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.InformarRemisionMJUResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.RespuestaComunicacionResultadoEnvioMJUType informarRemisionMJU(
      @WebParam(name = "peticionComunicacionResultadoEnvioMJUType",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.PeticionComunicacionResultadoEnvioMJUType peticionComunicacionResultadoEnvioMJUType)
      throws InsideWSException;

  @WebResult(name = "ExpedienteInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "crearVistaCerradaExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.CrearVistaCerradaExpediente")
  @WebMethod(action = "urn:crearVistaCerradaExpediente")
  @ResponseWrapper(localName = "crearVistaCerradaExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.CrearVistaCerradaExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteInsideInfo crearVistaCerradaExpediente(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador)
      throws InsideWSException;

  @WebResult(name = "resultados", targetNamespace = "")
  @RequestWrapper(localName = "buscarDocumentos",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.BuscarDocumentos")
  @WebMethod(action = "urn:buscarDocumentos")
  @ResponseWrapper(localName = "buscarDocumentosResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.BuscarDocumentosResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.DocumentoResultadoBusqueda buscarDocumentos(
      @WebParam(name = "consulta",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.ConsultaWsInside consulta,
      @WebParam(name = "limite", targetNamespace = "") int limite,
      @WebParam(name = "pagina", targetNamespace = "") int pagina) throws InsideWSException;

  @WebResult(name = "resultados", targetNamespace = "")
  @RequestWrapper(localName = "buscarExpedientes",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.BuscarExpedientes")
  @WebMethod(action = "urn:buscarExpedientes")
  @ResponseWrapper(localName = "buscarExpedientesResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.BuscarExpedientesResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteResultadoBusqueda buscarExpedientes(
      @WebParam(name = "consulta",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.ConsultaWsInside consulta,
      @WebParam(name = "limite", targetNamespace = "") int limite,
      @WebParam(name = "pagina", targetNamespace = "") int pagina) throws InsideWSException;

  @WebResult(name = "DocumentoInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "altaDocumentoEniXml",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaDocumentoEniXml")
  @WebMethod(action = "urn:altaDocumentoEniXml")
  @ResponseWrapper(localName = "altaDocumentoEniXmlResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaDocumentoEniXmlResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.DocumentoInsideInfo altaDocumentoEniXml(
      @WebParam(name = "documentoEniFile",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoDocumentoEniFileInside documentoEniFile)
      throws InsideWSException;

  @WebResult(name = "ExpedienteInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "desvincularDocumentosEnExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.DesvincularDocumentosEnExpediente")
  @WebMethod(action = "urn:desvincularDocumentosEnExpediente")
  @ResponseWrapper(localName = "desvincularDocumentosEnExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.DesvincularDocumentosEnExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteInsideInfo desvincularDocumentosEnExpediente(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador,
      @WebParam(name = "identificadorDocumento",
          targetNamespace = "") java.util.List<java.lang.String> identificadorDocumento,
      @WebParam(name = "ruta", targetNamespace = "") java.lang.String ruta)
      throws InsideWSException;

  @WebResult(name = "expedienteEniFile", targetNamespace = "")
  @RequestWrapper(localName = "getExpedienteEniFile",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetExpedienteEniFile")
  @WebMethod(action = "urn:getExpedienteEniFile")
  @ResponseWrapper(localName = "getExpedienteEniFileResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetExpedienteEniFileResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.TipoExpedienteEniFileInside getExpedienteEniFile(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador,
      @WebParam(name = "visualizacionIndice", targetNamespace = "") boolean visualizacionIndice)
      throws InsideWSException;

  @WebResult(name = "ExpedienteInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "modificaExpedienteEni",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.ModificaExpedienteEni")
  @WebMethod(action = "urn:modificaExpedienteEni")
  @ResponseWrapper(localName = "modificaExpedienteEniResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.ModificaExpedienteEniResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteInsideInfo modificaExpedienteEni(
      @WebParam(name = "expediente",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoExpediente expediente,
      @WebParam(name = "metadatosAdicionales",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoMetadatosAdicionales metadatosAdicionales)
      throws InsideWSException;

  @WebResult(name = "firmasCSV", targetNamespace = "")
  @RequestWrapper(localName = "getFirmasEniCSVDocumento",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetFirmasEniCSVDocumento")
  @WebMethod(action = "urn:getFirmasEniCSVDocumento")
  @ResponseWrapper(localName = "getFirmasEniCSVDocumentoResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetFirmasEniCSVDocumentoResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.Firmas getFirmasEniCSVDocumento(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador,
      @WebParam(name = "version", targetNamespace = "") java.lang.Integer version)
      throws InsideWSException;

  @WebResult(name = "indice", targetNamespace = "")
  @RequestWrapper(localName = "getIndiceExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetIndiceExpediente")
  @WebMethod(action = "urn:getIndiceExpediente")
  @ResponseWrapper(localName = "getIndiceExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetIndiceExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.TipoIndice getIndiceExpediente(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador)
      throws InsideWSException;

  @WebResult(name = "numeroBytes", targetNamespace = "")
  @RequestWrapper(localName = "getNumeroBytesDocumentoFirmado",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetNumeroBytesDocumentoFirmado")
  @WebMethod(action = "urn:getNumeroBytesDocumentoFirmado")
  @ResponseWrapper(localName = "getNumeroBytesDocumentoFirmadoResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetNumeroBytesDocumentoFirmadoResponse")
  public java.lang.Integer getNumeroBytesDocumentoFirmado(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador)
      throws InsideWSException;

  @WebResult(name = "RespuestaAccesoIndiceExpedienteType", targetNamespace = "")
  @RequestWrapper(localName = "accesoIndiceExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AccesoIndiceExpediente")
  @WebMethod(action = "urn:accesoIndiceExpediente")
  @ResponseWrapper(localName = "accesoIndiceExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AccesoIndiceExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.RespuestaAccesoIndiceExpedienteType accesoIndiceExpediente(
      @WebParam(name = "peticionAccesoIndiceExpedienteType",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.PeticionAccesoIndiceExpedienteType peticionAccesoIndiceExpedienteType)
      throws InsideWSException;

  @WebResult(name = "expediente", targetNamespace = "")
  @RequestWrapper(localName = "getExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetExpediente")
  @WebMethod(action = "urn:getExpediente")
  @ResponseWrapper(localName = "getExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.GetExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.TipoExpedienteInside getExpediente(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador,
      @WebParam(name = "version", targetNamespace = "") java.lang.Integer version)
      throws InsideWSException;

  @WebResult(name = "ExpedienteInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "vincularDocumentosEnExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.VincularDocumentosEnExpediente")
  @WebMethod(action = "urn:vincularDocumentosEnExpediente")
  @ResponseWrapper(localName = "vincularDocumentosEnExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.VincularDocumentosEnExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteInsideInfo vincularDocumentosEnExpediente(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador,
      @WebParam(name = "identificadorDocumento",
          targetNamespace = "") java.util.List<java.lang.String> identificadorDocumento,
      @WebParam(name = "ruta", targetNamespace = "") java.lang.String ruta)
      throws InsideWSException;

  @RequestWrapper(localName = "eliminarExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.EliminarExpediente")
  @WebMethod(action = "urn:eliminarExpediente")
  @ResponseWrapper(localName = "eliminarExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.EliminarExpedienteResponse")
  public void eliminarExpediente(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador)
      throws InsideWSException;

  @WebResult(name = "ExpedienteInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "cambiaEstadoExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.CambiaEstadoExpediente")
  @WebMethod(action = "urn:cambiaEstadoExpediente")
  @ResponseWrapper(localName = "cambiaEstadoExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.CambiaEstadoExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteInsideInfo cambiaEstadoExpediente(
      @WebParam(name = "identificador", targetNamespace = "") java.lang.String identificador,
      @WebParam(name = "estado",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.EnumeracionEstados estado)
      throws InsideWSException;

  @WebResult(name = "RespuestaAccesoDocumentoExpedienteType", targetNamespace = "")
  @RequestWrapper(localName = "accesoDocumentoExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AccesoDocumentoExpediente")
  @WebMethod(action = "urn:accesoDocumentoExpediente")
  @ResponseWrapper(localName = "accesoDocumentoExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AccesoDocumentoExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.RespuestaAccesoDocumentoExpedienteType accesoDocumentoExpediente(
      @WebParam(name = "peticionAccesoDocumentoExpedienteType",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.PeticionAccesoDocumentoExpedienteType peticionAccesoDocumentoExpedienteType)
      throws InsideWSException;

  @WebResult(name = "ExpedienteInsideInfo", targetNamespace = "")
  @RequestWrapper(localName = "altaExpedienteEni",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaExpedienteEni")
  @WebMethod(action = "urn:altaExpedienteEni")
  @ResponseWrapper(localName = "altaExpedienteEniResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.AltaExpedienteEniResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.ExpedienteInsideInfo altaExpedienteEni(
      @WebParam(name = "expediente",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoExpediente expediente,
      @WebParam(name = "metadatosAdicionales",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.TipoMetadatosAdicionales metadatosAdicionales)
      throws InsideWSException;
}
