/*
 * Copyright (C) 2016 MINHAP, Gobierno de España This program is licensed and may be used, modified
 * and redistributed under the terms of the European Public License (EUPL), either version 1.1 or
 * (at your option) any later version as soon as they are approved by the European Commission.
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package es.mpt.dsic.inside.remisionnube.client.modelo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3 2016-10-13T09:46:15.341+02:00 Generated source
 * version: 3.0.3
 * 
 */
@WebService(targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
    name = "PuntoRemisionWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface PuntoRemisionWebService {

  @WebResult(name = "RespuestaInformarAccesoExpedienteType", targetNamespace = "")
  @RequestWrapper(localName = "informarAccesoExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.InformarAccesoExpediente")
  @WebMethod(action = "urn:informarAccesoExpediente")
  @ResponseWrapper(localName = "informarAccesoExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.InformarAccesoExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.RespuestaInformarAccesoExpedienteType informarAccesoExpediente(
      @WebParam(name = "peticionInformarAccesoExpedienteType",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.PeticionInformarAccesoExpedienteType peticionInformarAccesoExpedienteType)
      throws InsideWSException;

  @WebResult(name = "RespuestaSolicitarAccesoExpedienteType", targetNamespace = "")
  @RequestWrapper(localName = "solicitarAccesoExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.SolicitarAccesoExpediente")
  @WebMethod(action = "urn:solicitarAccesoExpediente")
  @ResponseWrapper(localName = "solicitarAccesoExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.SolicitarAccesoExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.RespuestaSolicitarAccesoExpedienteType solicitarAccesoExpediente(
      @WebParam(name = "peticionSolicitarAccesoExpedienteType",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.PeticionSolicitarAccesoExpedienteType peticionSolicitarAccesoExpedienteType)
      throws InsideWSException;

  @WebResult(name = "RespuestaComunicacionTokenExpedienteType", targetNamespace = "")
  @RequestWrapper(localName = "comunicacionTokenExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.ComunicacionTokenExpediente")
  @WebMethod(action = "urn:comunicacionTokenExpediente")
  @ResponseWrapper(localName = "comunicacionTokenExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.inside.remisionnube.client.modelo.ComunicacionTokenExpedienteResponse")
  public es.mpt.dsic.inside.remisionnube.client.modelo.RespuestaComunicacionTokenExpedienteType comunicacionTokenExpediente(
      @WebParam(name = "peticionComunicacionTokenExpedienteType",
          targetNamespace = "") es.mpt.dsic.inside.remisionnube.client.modelo.PeticionComunicacionTokenExpedienteType peticionComunicacionTokenExpedienteType)
      throws InsideWSException;
}
