/* Copyright (C) 2016 MINHAP, Gobierno de España
   This program is licensed and may be used, modified and redistributed under the terms
   of the European Public License (EUPL), either version 1.1 or (at your
   option) any later version as soon as they are approved by the European Commission.
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
   or implied. See the License for the specific language governing permissions and
   more details.
   You should have received a copy of the EUPL1.1 license
   along with this program; if not, you may find it at
   http://joinup.ec.europa.eu/software/page/eupl/licence-eupl */

package es.mpt.dsic.eeutil.client.utilFirma;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import es.mpt.dsic.eeutil.client.model.InSideException;
import es.mpt.dsic.eeutil.client.model.ObjectFactory;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-12-16T16:48:48.638+01:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://service.ws.inside.dsic.mpt.es/", name = "EeUtilService")
@XmlSeeAlso({ObjectFactory.class})
public interface EeUtilService {

    @WebResult(name = "CSVResult", targetNamespace = "")
    @RequestWrapper(localName = "generarCSV", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.client.model.GenerarCSV")
    @WebMethod(action = "urn:GenerarCSV")
    @ResponseWrapper(localName = "generarCSVResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.client.model.GenerarCSVResponse")
    public java.lang.String generarCSV(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.client.model.ApplicationLogin aplicacionInfo,
        @WebParam(name = "CSVInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.client.model.CSVInfo csvInfo
    ) throws InSideException;

    @WebResult(name = "CSVResult", targetNamespace = "")
    @RequestWrapper(localName = "generarCSVAmbito", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.client.model.GenerarCSVAmbito")
    @WebMethod(action = "urn:generarCSVAmbito")
    @ResponseWrapper(localName = "generarCSVAmbitoResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.client.model.GenerarCSVAmbitoResponse")
    public java.lang.String generarCSVAmbito(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.client.model.ApplicationLogin aplicacionInfo,
        @WebParam(name = "CSVInfoAmbito", targetNamespace = "")
        es.mpt.dsic.eeutil.client.model.CSVInfoAmbito csvInfoAmbito
    ) throws InSideException;

    @WebResult(name = "infoFirma", targetNamespace = "")
    @RequestWrapper(localName = "generarJustificanteFirma", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.client.model.GenerarJustificanteFirma")
    @WebMethod(action = "urn:generarJustificanteFirma")
    @ResponseWrapper(localName = "generarJustificanteFirmaResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.client.model.GenerarJustificanteFirmaResponse")
    public es.mpt.dsic.eeutil.client.model.CopiaInfoFirmaSalida generarJustificanteFirma(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.client.model.ApplicationLogin aplicacionInfo,
        @WebParam(name = "copiaInfoFirma", targetNamespace = "")
        es.mpt.dsic.eeutil.client.model.CopiaInfoFirma copiaInfoFirma,
        @WebParam(name = "simpleFormat", targetNamespace = "")
        boolean simpleFormat
    ) throws InSideException;

    @WebResult(name = "estadoInfo", targetNamespace = "")
    @RequestWrapper(localName = "generarCopia", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.client.model.GenerarCopia")
    @WebMethod(action = "urn:GenerarCopia")
    @ResponseWrapper(localName = "generarCopiaResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.client.model.GenerarCopiaResponse")
    public es.mpt.dsic.eeutil.client.model.CopiaInfo generarCopia(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.client.model.ApplicationLogin aplicacionInfo,
        @WebParam(name = "copiaInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.client.model.CopiaInfo copiaInfo,
        @WebParam(name = "simpleFormat", targetNamespace = "")
        boolean simpleFormat
    ) throws InSideException;

    @WebResult(name = "estadoInfoFirma", targetNamespace = "")
    @RequestWrapper(localName = "generarCopiaFirma", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.client.model.GenerarCopiaFirma")
    @WebMethod(action = "urn:GenerarCopiaFirma")
    @ResponseWrapper(localName = "generarCopiaFirmaResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.client.model.GenerarCopiaFirmaResponse")
    public es.mpt.dsic.eeutil.client.model.CopiaInfo generarCopiaFirma(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.client.model.ApplicationLogin aplicacionInfo,
        @WebParam(name = "copiaInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.client.model.CopiaInfo copiaInfo,
        @WebParam(name = "firmaInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.client.model.ListaFirmaInfo firmaInfo,
        @WebParam(name = "simpleFormat", targetNamespace = "")
        boolean simpleFormat
    ) throws InSideException;

    @WebResult(name = "estadoInfoFirma", targetNamespace = "")
    @RequestWrapper(localName = "generarCopiaFirmaNormalizada", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.client.model.GenerarCopiaFirmaNormalizada")
    @WebMethod(action = "urn:GenerarCopiaFirmaNormalizada")
    @ResponseWrapper(localName = "generarCopiaFirmaNormalizadaResponse", targetNamespace = "http://service.ws.inside.dsic.mpt.es/", className = "es.mpt.dsic.eeutil.client.model.GenerarCopiaFirmaNormalizadaResponse")
    public es.mpt.dsic.eeutil.client.model.CopiaInfo generarCopiaFirmaNormalizada(
        @WebParam(name = "aplicacionInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.client.model.ApplicationLogin aplicacionInfo,
        @WebParam(name = "copiaInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.client.model.CopiaInfo copiaInfo,
        @WebParam(name = "firmaInfo", targetNamespace = "")
        es.mpt.dsic.eeutil.client.model.ListaFirmaInfo firmaInfo,
        @WebParam(name = "simpleFormat", targetNamespace = "")
        boolean simpleFormat
    ) throws InSideException;
}
