/*
 * Copyright (C) 2016 MINHAP, Gobierno de España This program is licensed and may be used, modified
 * and redistributed under the terms of the European Public License (EUPL), either version 1.1 or
 * (at your option) any later version as soon as they are approved by the European Commission.
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package es.mpt.dsic.inside.service.portales.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.3 2017-02-20T11:01:55.340+01:00 Generated source
 * version: 3.0.3
 * 
 */
@WebService(targetNamespace = "https://ssweb.seap.minhap.es/portalEELL/",
    name = "consultaCargosPortalEELLWSPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ConsultaCargosPortalEELLWSPortType {

  @WebResult(name = "results", targetNamespace = "https://ssweb.seap.minhap.es/portalEELL/",
      partName = "results")
  @WebMethod(action = "https://ssweb.seap.minhap.es/portalEELL/comprobarCargosUsuario")
  public CargosWsObject comprobarCargosUsuario(@WebParam(partName = "AuthHeader",
      mode = WebParam.Mode.INOUT, header = true, name = "AuthHeaderElement",
      targetNamespace = "https://ssweb.seap.minhap.es/portalEELL/") javax.xml.ws.Holder<AuthHeader> authHeader,
      @WebParam(partName = "nif", name = "nif") java.lang.String nif);
}
