DROP TABLE AuditoriaAccesoDocumento;
CREATE TABLE AuditoriaAccesoDocumento (id int NOT NULL, DIR3_Peticionario varchar(256) NOT NULL, Usuario_Peticionario varchar(256), Id_Peticion varchar(256) NOT NULL, Id_Documento varchar(256) NOT NULL, Fecha timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE AuditoriaFirmaServidor;
CREATE TABLE AuditoriaFirmaServidor (id int NOT NULL, elemento varchar(3) NOT NULL, identificador varchar(255) NOT NULL, usuario varchar(255) NOT NULL, created_at timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE AuditoriaRespuestaEnvioJusticia;
CREATE TABLE AuditoriaRespuestaEnvioJusticia (id int NOT NULL, identificador_expediente varchar(255) NOT NULL, id_unidad int, id_procedimiento int, auditoriaEsb_marcaTiempo varchar(255) NOT NULL, codigo_envio varchar(255) NOT NULL, PRIMARY KEY (id), CONSTRAINT id UNIQUE (id), INDEX fk_AuditoriaRespuestaEnvioJusticia_UnidadOrganica_idx (id_unidad), INDEX fk_AuditoriaRespuestaEnvioJusticia_NumeroProcedimiento_idx (id_procedimiento)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE AuditoriaToken;
CREATE TABLE AuditoriaToken (id int NOT NULL, id_token int NOT NULL, nifUsuarioUso varchar(255) NOT NULL, acta blob NOT NULL, justificante mediumblob NOT NULL, fechaUso timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, dir3UsuarioUso varchar(256), nombreDir3UsuarioUso varchar(256), idRolUso int, descripcionRolUso varchar(256), PRIMARY KEY (id), INDEX fk_AuditoriaToken_TokenInside_idx (id_token)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE ComunicacionTokenExpediente;
CREATE TABLE ComunicacionTokenExpediente (id int NOT NULL, Dir3Destino varchar(255) NOT NULL, IdPeticion varchar(255) NOT NULL, Usuario_Peticionario varchar(255), Asunto varchar(255), Token_IdExpEni varchar(255) NOT NULL, Token_CSV varchar(255) NOT NULL, Token_UUID varchar(255) NOT NULL, FechaPeticion timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, Resultado varchar(255), EndpointRemitente varchar(255) NOT NULL, IndiceExpediente blob, UrlAccesoWeb varchar(255), RJNig varchar(19), RJClaseProcedimiento varchar(3), RJAnyoProcedimiento varchar(4), RJNumeroProcedimiento varchar(255), RJDir3Remitente varchar(255), RJDescripcion varchar(255), NIntentos int, Correcto varchar(1), FechaProximoIntento timestamp DEFAULT '0000-00-00 00:00:00', ResultadoNotificado varchar(1), PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE CredencialesEeutil;
CREATE TABLE CredencialesEeutil (id int DEFAULT '0' NOT NULL, idAplicacionInterna int NOT NULL, idAplicacion varchar(255) NOT NULL, password varchar(255) NOT NULL, PRIMARY KEY (id), CONSTRAINT idAplicacionInterna UNIQUE (idAplicacionInterna)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE DocumentoInside;
CREATE TABLE DocumentoInside (id int DEFAULT '0' NOT NULL, identificador varchar(255) NOT NULL, identificador_repositorio varchar(255), version int DEFAULT '1' NOT NULL, fechaVersion timestamp DEFAULT '0000-00-00 00:00:00', versionNti varchar(255), fechaCaptura timestamp DEFAULT '0000-00-00 00:00:00' NULL, origen tinyint(1) DEFAULT '0', nombreFormato varchar(255), tipoMime varchar(255), tipoDocumental varchar(255), estadoElaboracion varchar(255), identificadorDocumentoOrigen varchar(255), identificadorEnDocumento varchar(255), referencia varchar(255), created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL, fechaBaja timestamp NULL, PRIMARY KEY (id), CONSTRAINT identificador_version UNIQUE (identificador, version)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE DocumentoInsideFirmas;
CREATE TABLE DocumentoInsideFirmas (id int DEFAULT '0' NOT NULL, id_documento int NOT NULL, id_firma int NOT NULL, PRIMARY KEY (id), INDEX FK_DocumentoInsideFirmas_Documento (id_documento), INDEX FK_DocumentoInsideFirmas_Firma (id_firma)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE DocumentoInsideMetAdic;
CREATE TABLE DocumentoInsideMetAdic (id int DEFAULT '0' NOT NULL, id_documento int, nombre varchar(255), valor longtext, PRIMARY KEY (id), INDEX FK_DocumentoInsideMetadatosAdicionales_Documento (id_documento)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE DocumentoInsideOrgano;
CREATE TABLE DocumentoInsideOrgano (id int DEFAULT '0' NOT NULL, id_documento int NOT NULL, organo varchar(255) NOT NULL, PRIMARY KEY (id), INDEX FK_DocumentoInsideOrgano_Documento (id_documento)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE DocumentoUnidad;
CREATE TABLE DocumentoUnidad (id int NOT NULL, identificador varchar(255) NOT NULL, id_unidad int NOT NULL, fechaVersion timestamp NULL, id_procedimiento int, PRIMARY KEY (id), INDEX fk_DocumentoUnidad_DocumentoInside_idx (identificador), INDEX fk_DocumentoUnidad_UnidadOrganica_idx (id_unidad), INDEX fk_DocumentoUnidad_NumeroProcedimiento_idx (id_procedimiento)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE DsicDir3Oficina;
CREATE TABLE DsicDir3Oficina (id int NOT NULL AUTO_INCREMENT, Codigo_Oficina varchar(10) NOT NULL, Denominacion_Oficina text NOT NULL, Externo_Fuente varchar(40), Codigo_Unidad_Responsable varchar(9), Nivel_Administracion varchar(1) NOT NULL, Indicador_Oficina_Registro varchar(1), Indicador_Oficina_Informacion varchar(1), Indicador_Oficina_Tramitacion varchar(1), Indicador_Registro_Electronico varchar(1), Indicador_Interop_Sin_Restriccion varchar(1), Indicador_Interop_Local_Estatal varchar(1), Indicador_Interop_Local_Autonomica_res varchar(1), Indicador_Interop_Local_Local_res varchar(1), Indicador_Interop_Local_Autonomica_gen varchar(1), Indicador_Interop_Local_Local_gen varchar(1), Indicador_Interop_Ayuntamiento_Ayuntamiento varchar(1), Indicador_SIR varchar(1), Tipo_Via varchar(15) NOT NULL, Nombre_Via text NOT NULL, Numero_Via varchar(20) NOT NULL, Codigo_Postal varchar(14) NOT NULL, Resto_Direccion varchar(255), Localidad text, Provincia varchar(50), Isla varchar(2), Comunidad_Autonoma varchar(100), Pais varchar(100) NOT NULL, Direccion_Extranjera varchar(200), Estado_Oficina varchar(1), Fecha_Alta datetime, Fecha_Anulacion datetime, Fecha_Extincion datetime, timestamp datetime NOT NULL, PRIMARY KEY (id), CONSTRAINT oficina_unica_idx UNIQUE (Codigo_Oficina)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE DsicDir3OficinaRelacion;
CREATE TABLE DsicDir3OficinaRelacion (id int NOT NULL AUTO_INCREMENT, Codigo_Oficina_Anterior varchar(10), Denominacion_Oficina_Anterior text, Codigo_Oficina_Ultima varchar(10), Denominacion_Oficina_Ultima text, timestamp datetime NOT NULL, PRIMARY KEY (id), CONSTRAINT relacion_oficina_unica_idx UNIQUE (Codigo_Oficina_Anterior, Codigo_Oficina_Ultima)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE DsicDir3UnidadOficinaRelacion;
CREATE TABLE DsicDir3UnidadOficinaRelacion (id int NOT NULL AUTO_INCREMENT, Codigo_Unidad_Organica varchar(9), Denominacion_Unidad_Organica text, Codigo_Oficina varchar(10), Denominacion_Oficina text, Estado_Relacion varchar(1), timestamp datetime NOT NULL, PRIMARY KEY (id), CONSTRAINT relacion_unidad_oficina_unica_idx UNIQUE (Codigo_Unidad_Organica, Codigo_Oficina)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE DsicDir3UnidadOrganica;
CREATE TABLE DsicDir3UnidadOrganica (id int NOT NULL AUTO_INCREMENT, Codigo_Unidad_Organica varchar(10) NOT NULL, Nombre_Unidad_Organica varchar(255) NOT NULL, Nivel_Administracion tinyint NOT NULL, Indicador_Entidad_Derecho_Publico varchar(1) NOT NULL, Codigo_Externo varchar(10), Codigo_Unidad_Superior_Jerarquica varchar(10) NOT NULL, Denominacion_Unidad_Superior_Jerarquica varchar(255) NOT NULL, Codigo_Unidad_Organica_Raiz varchar(10) NOT NULL, Denominacion_Unidad_Organica_Raiz varchar(255) NOT NULL, Codigo_Unidad_Raiz_Entidad_Derecho_Publico varchar(10), Denominacion_Unidad_Raiz_Entidad_Derecho_Publico varchar(255), Nivel_Jerarquico tinyint NOT NULL, Estado varchar(1) NOT NULL, Fecha_Alta datetime, Fecha_Baja datetime, Fecha_Anulacion datetime, Fecha_Extincion datetime, timestamp datetime NOT NULL, PRIMARY KEY (id), CONSTRAINT unidad_unica_idx UNIQUE (Codigo_Unidad_Organica)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE DsicDir3UnidadRelacion;
CREATE TABLE DsicDir3UnidadRelacion (id int NOT NULL AUTO_INCREMENT, Codigo_Organismo_Anterior varchar(10) NOT NULL, Denominacion_Organismo_Anterior varchar(255) NOT NULL, Codigo_Organismo_Ultima varchar(10) NOT NULL, Denominacion_Organismo_Ultima varchar(255) NOT NULL, timestamp datetime NOT NULL, PRIMARY KEY (id), CONSTRAINT relacion_unica_idx UNIQUE (Codigo_Organismo_Anterior, Codigo_Organismo_Ultima)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE EstructuraCarpetaInside;
CREATE TABLE EstructuraCarpetaInside (id int NOT NULL, identificador_estructura varchar(255) NOT NULL, id_unidad int, id_procedimiento int, id_carpeta_estructura int, PRIMARY KEY (id), CONSTRAINT id UNIQUE (id), INDEX FK_ExpInsideIndice_CarInd (id_carpeta_estructura)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE ExpedienteInside;
CREATE TABLE ExpedienteInside (id int DEFAULT '0' NOT NULL, identificador varchar(255) NOT NULL, identificador_repositorio varchar(255), version int DEFAULT '1' NOT NULL, fechaVersion timestamp DEFAULT '0000-00-00 00:00:00', versionNti varchar(255), fechaAperturaExpediente timestamp DEFAULT '0000-00-00 00:00:00' NULL, clasificacion varchar(255), estado varchar(255), id_indice int NOT NULL, created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL, fechaBaja timestamp NULL, PRIMARY KEY (id), CONSTRAINT identificador_version UNIQUE (identificador, version), INDEX FK_ExpedienteInside_Indice (id_indice)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE ExpedienteInsideIndice;
CREATE TABLE ExpedienteInsideIndice (id int DEFAULT '0' NOT NULL, identificador_expediente varchar(255), id_expediente_vinculado int, fecha_indice_electronico timestamp NULL, id_expediente_indizado int, id_carpeta_indizada int, orden int(3), created_at timestamp DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id), CONSTRAINT id UNIQUE (id), INDEX FK_ExpedienteInsideIndice_ExpedienteIndizado (id_expediente_indizado), INDEX FK_ExpedienteInsideIndice_CarpetaIndizada (id_carpeta_indizada), INDEX FK_ExpedienteInsideIndice_ExpedienteVinculado (id_expediente_vinculado)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE ExpedienteInsideIndiceCarInd;
CREATE TABLE ExpedienteInsideIndiceCarInd (id int DEFAULT '0' NOT NULL, identificador_carpeta varchar(255) NOT NULL, id_expediente_indizado int, id_carpeta_indizada int, orden int(3) NOT NULL, created_at timestamp DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id), INDEX FK_ExpedienteInsideIndiceCarpetaIndizada_Carpeta (id_carpeta_indizada), INDEX FK_ExpedienteInsideIndiceCarpetaIndizada_ExpedienteIndizado (id_expediente_indizado)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE ExpedienteInsideIndiceDocInd;
CREATE TABLE ExpedienteInsideIndiceDocInd (id int DEFAULT '0' NOT NULL, valorHuella varchar(255), funcionResumen varchar(255), fechaIncorporacionExpediente timestamp NULL, identificadorDocumento varchar(255), id_expediente_indizado int, id_carpeta_indizada int, orden_documento_expediente int(3) DEFAULT '-1', orden int(3) NOT NULL, created_at timestamp DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id), INDEX FK_ExpedienteInsideIndiceDocumentoIndizado_Expediente (id_expediente_indizado), INDEX FK_ExpedienteInsideIndiceDocumentoIndizado_CarpetaIndizada (id_carpeta_indizada)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE ExpedienteInsideIndiceFirmas;
CREATE TABLE ExpedienteInsideIndiceFirmas (id int DEFAULT '0' NOT NULL, id_expediente int NOT NULL, id_firmaInside int NOT NULL, PRIMARY KEY (id), INDEX FK_ExpedienteInsideIndiceFirmas_Firma (id_firmaInside), INDEX FK_ExpedienteInsideIndiceFirmas_Expediente (id_expediente)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE ExpedienteInsideInteresado;
CREATE TABLE ExpedienteInsideInteresado (id int DEFAULT '0' NOT NULL, id_expediente int NOT NULL, interesado varchar(255) NOT NULL, PRIMARY KEY (id), INDEX FK_ExpedienteInsideInteresado_Expediente (id_expediente)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE ExpedienteInsideMetAdic;
CREATE TABLE ExpedienteInsideMetAdic (id int DEFAULT '0' NOT NULL, id_expediente int, nombre varchar(255), valor longtext, PRIMARY KEY (id), INDEX FK_ExpedienteInsideMetadatosAdicionales_Expediente (id_expediente)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE ExpedienteInsideOrgano;
CREATE TABLE ExpedienteInsideOrgano (id int DEFAULT '0' NOT NULL, id_expediente int NOT NULL, organo varchar(255) NOT NULL, PRIMARY KEY (id), INDEX FK_ExpedienteInsideOrgano_Expediente (id_expediente)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE ExpedienteInsideRespuestaEnvioJusticia;
CREATE TABLE ExpedienteInsideRespuestaEnvioJusticia (id int DEFAULT '0' NOT NULL, id_expediente_envio int, AuditoriaEsb_aplicacion varchar(255), AuditoriaEsb_modulo varchar(255), AuditoriaEsb_servicio varchar(255), AuditoriaEsb_marcaTiempo varchar(35), ack varchar(5), codigoEnvio varchar(255), mensaje varchar(1000), codigoUnidadOrganoRemitente varchar(10), PRIMARY KEY (id), INDEX FK_ExpedienteInsideResultadoEnvioJusticia_Expediente (id_expediente_envio)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE ExpedienteNoInsideRespuestaEnvioJusticia;
CREATE TABLE ExpedienteNoInsideRespuestaEnvioJusticia (id int DEFAULT '0' NOT NULL, id_expediente_envio varchar(255), AuditoriaEsb_aplicacion varchar(255), AuditoriaEsb_modulo varchar(255), AuditoriaEsb_servicio varchar(255), AuditoriaEsb_marcaTiempo varchar(35), ack varchar(5), codigoEnvio varchar(255), mensaje varchar(1000), codigoUnidadOrganoRemitente varchar(10), PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE ExpedienteToken;
CREATE TABLE ExpedienteToken (id int NOT NULL, id_usuario int NOT NULL, identificador varchar(255) NOT NULL, csv varchar(255) NOT NULL, uuid varchar(255) NOT NULL, fechaCaducidad date, dir3 varchar(255) NOT NULL, nifs varchar(255) NOT NULL, asunto varchar(255), fechaCreacion timestamp NULL, PRIMARY KEY (id), INDEX fk_ExpedienteToken_UsuarioInside_idx (id_usuario), INDEX fk_ExpedienteToken_ExpedienteInside_idx (identificador)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE ExpedienteUnidad;
CREATE TABLE ExpedienteUnidad (id int NOT NULL, identificador varchar(255) NOT NULL, id_unidad int NOT NULL, fechaVersion timestamp NULL, estadoExpediente varchar(255) NOT NULL, id_procedimiento int, PRIMARY KEY (id), INDEX fk_ExpedienteUnidad_ExpedienteInside_idx (identificador), INDEX fk_ExpedienteUnidad_UnidadOrganica_idx (id_unidad), INDEX fk_ExpedienteUnidad_NumeroProcedimiento_idx (id_procedimiento)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE FirmaInside;
CREATE TABLE FirmaInside (id int DEFAULT '0' NOT NULL, tipoFirma varchar(255) NOT NULL, identificadorRepositorio varchar(255), valorCSV varchar(255), regulacionCSV varchar(255), tipoMime varchar(255), referencia varchar(255), signature tinyint(1) DEFAULT '0', timestamp timestamp DEFAULT CURRENT_TIMESTAMP NULL, identificadorEnDocumento varchar(255), orden int(10), contenido mediumblob, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE GeneradorClaves;
CREATE TABLE GeneradorClaves (GenName varchar(255) NOT NULL, GenValue int NOT NULL, PRIMARY KEY (GenName)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE GeneradorIdInside;
CREATE TABLE GeneradorIdInside (id int NOT NULL, elemento varchar(3) NOT NULL, id_unidad int NOT NULL, numeroId int NOT NULL, PRIMARY KEY (id), INDEX fk_GeneradorIdInside_UnidadOrganica_idx (id_unidad)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE InsideRol;
CREATE TABLE InsideRol (id int NOT NULL, descripcion varchar(256) NOT NULL, descripcionLarga varchar(256) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE InsideWsAplicacion;
CREATE TABLE InsideWsAplicacion (id int DEFAULT '0' NOT NULL, nombre varchar(255) NOT NULL, passwordHash varchar(255) NOT NULL, activo tinyint(1) DEFAULT '1' NOT NULL, altaExpediente tinyint(1) DEFAULT '1' NOT NULL, modificarExpediente tinyint(1) DEFAULT '1' NOT NULL, leerExpediente tinyint(1) DEFAULT '1' NOT NULL, altaDocumento tinyint(1) DEFAULT '1' NOT NULL, modificarDocumento tinyint(1) DEFAULT '1' NOT NULL, leerDocumento tinyint(1) DEFAULT '1' NOT NULL, fechaCreacion timestamp DEFAULT CURRENT_TIMESTAMP, administrarPermisos tinyint(1) DEFAULT '0' NOT NULL, email varchar(255), telefono varchar(255), responsable varchar(255), serialNumberCertificado varchar(255), PRIMARY KEY (id), CONSTRAINT nombre UNIQUE (nombre)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE InsideWsAudit;
CREATE TABLE InsideWsAudit (id int DEFAULT '0' NOT NULL, id_aplicacion int NOT NULL, id_expediente int, id_documento int, timestamp timestamp DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE LogAccesoGenerador;
CREATE TABLE LogAccesoGenerador (id int DEFAULT '0' NOT NULL, nif varchar(10) NOT NULL, timestamp timestamp DEFAULT CURRENT_TIMESTAMP, ip varchar(255), server varchar(255), user_agent varchar(255)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE LogAccesoVisor;
CREATE TABLE LogAccesoVisor (id int NOT NULL AUTO_INCREMENT, nif varchar(10) NOT NULL, timestamp timestamp DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE MensajeUsuario;
CREATE TABLE MensajeUsuario (id int NOT NULL, texto varchar(255) NOT NULL, activo tinyint(1) DEFAULT '1' NOT NULL, fechaCreacion timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, fechaModificacion timestamp NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE NumeroProcedimiento;
CREATE TABLE NumeroProcedimiento (id int NOT NULL, numeroProcedimiento varchar(255) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE PUJ_CREDENTIALS;
CREATE TABLE PUJ_CREDENTIALS (Id int NOT NULL, APLICACIONID varchar(255) NOT NULL, PASSWORDHASH varchar(255) NOT NULL, PRIMARY KEY (Id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE QRTZ_BLOB_TRIGGERS;
CREATE TABLE QRTZ_BLOB_TRIGGERS (TRIGGER_NAME varchar(80) NOT NULL, TRIGGER_GROUP varchar(80) NOT NULL, BLOB_DATA blob, PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE QRTZ_CALENDARS;
CREATE TABLE QRTZ_CALENDARS (CALENDAR_NAME varchar(80) NOT NULL, CALENDAR blob NOT NULL, PRIMARY KEY (CALENDAR_NAME)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE QRTZ_CRON_TRIGGERS;
CREATE TABLE QRTZ_CRON_TRIGGERS (TRIGGER_NAME varchar(80) NOT NULL, TRIGGER_GROUP varchar(80) NOT NULL, CRON_EXPRESSION varchar(80) NOT NULL, TIME_ZONE_ID varchar(80), PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE QRTZ_FIRED_TRIGGERS;
CREATE TABLE QRTZ_FIRED_TRIGGERS (ENTRY_ID varchar(95) NOT NULL, TRIGGER_NAME varchar(80) NOT NULL, TRIGGER_GROUP varchar(80) NOT NULL, IS_VOLATILE varchar(1) NOT NULL, INSTANCE_NAME varchar(80) NOT NULL, FIRED_TIME bigint(13) NOT NULL, STATE varchar(16) NOT NULL, JOB_NAME varchar(80), JOB_GROUP varchar(80), IS_STATEFUL varchar(1), REQUESTS_RECOVERY varchar(1), PRIMARY KEY (ENTRY_ID)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE QRTZ_JOB_DETAILS;
CREATE TABLE QRTZ_JOB_DETAILS (JOB_NAME varchar(80) NOT NULL, JOB_GROUP varchar(80) NOT NULL, DESCRIPTION varchar(120), JOB_CLASS_NAME varchar(128) NOT NULL, IS_DURABLE varchar(1) NOT NULL, IS_VOLATILE varchar(1) NOT NULL, IS_STATEFUL varchar(1) NOT NULL, REQUESTS_RECOVERY varchar(1) NOT NULL, JOB_DATA blob, PRIMARY KEY (JOB_NAME, JOB_GROUP)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE QRTZ_JOB_LISTENERS;
CREATE TABLE QRTZ_JOB_LISTENERS (JOB_NAME varchar(80) NOT NULL, JOB_GROUP varchar(80) NOT NULL, JOB_LISTENER varchar(80) NOT NULL, PRIMARY KEY (JOB_NAME, JOB_GROUP, JOB_LISTENER)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE QRTZ_LOCKS;
CREATE TABLE QRTZ_LOCKS (LOCK_NAME varchar(40) NOT NULL, PRIMARY KEY (LOCK_NAME)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE QRTZ_PAUSED_TRIGGER_GRPS;
CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (TRIGGER_GROUP varchar(80) NOT NULL, PRIMARY KEY (TRIGGER_GROUP)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE QRTZ_SCHEDULER_STATE;
CREATE TABLE QRTZ_SCHEDULER_STATE (INSTANCE_NAME varchar(80) NOT NULL, LAST_CHECKIN_TIME bigint(13) NOT NULL, CHECKIN_INTERVAL bigint(13) NOT NULL, RECOVERER varchar(80), PRIMARY KEY (INSTANCE_NAME)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE QRTZ_SIMPLE_TRIGGERS;
CREATE TABLE QRTZ_SIMPLE_TRIGGERS (TRIGGER_NAME varchar(80) NOT NULL, TRIGGER_GROUP varchar(80) NOT NULL, REPEAT_COUNT bigint(7) NOT NULL, REPEAT_INTERVAL bigint(12) NOT NULL, TIMES_TRIGGERED bigint(7) NOT NULL, PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE QRTZ_TRIGGERS;
CREATE TABLE QRTZ_TRIGGERS (TRIGGER_NAME varchar(80) NOT NULL, TRIGGER_GROUP varchar(80) NOT NULL, JOB_NAME varchar(80) NOT NULL, JOB_GROUP varchar(80) NOT NULL, IS_VOLATILE varchar(1) NOT NULL, DESCRIPTION varchar(120), NEXT_FIRE_TIME bigint(13), PREV_FIRE_TIME bigint(13), TRIGGER_STATE varchar(16) NOT NULL, TRIGGER_TYPE varchar(8) NOT NULL, START_TIME bigint(13) NOT NULL, END_TIME bigint(13), CALENDAR_NAME varchar(80), MISFIRE_INSTR smallint(2), JOB_DATA blob, PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP), INDEX JOB_NAME (JOB_NAME, JOB_GROUP)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE QRTZ_TRIGGER_LISTENERS;
CREATE TABLE QRTZ_TRIGGER_LISTENERS (TRIGGER_NAME varchar(80) NOT NULL, TRIGGER_GROUP varchar(80) NOT NULL, TRIGGER_LISTENER varchar(80) NOT NULL, PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_LISTENER)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE SolicitudAccesoExpAppUrl;
CREATE TABLE SolicitudAccesoExpAppUrl (id int NOT NULL, Dir3Padre varchar(256) NOT NULL, UrlDestinoPeticion varchar(256) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE SolicitudAccesoExpediente;
CREATE TABLE SolicitudAccesoExpediente (id int NOT NULL, DIR3_Peticionario varchar(256) NOT NULL, Id_Peticion varchar(256) NOT NULL, Usuario_Peticionario varchar(256), Asunto varchar(256) NOT NULL, IdExpedienteSolicitado varchar(256), CodigoSia int NOT NULL, EndpointRemitente varchar(256) NOT NULL, FechaPeticion timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, Resultado varchar(256), EnvioCorrecto varchar(1), SolicitudTokenDenegada varchar(1), Metadatos blob, Dir3ExpedienteSolicitado varchar(256), NifUsuarioGeneraToken varchar(256), PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE UnidadAplicacionEeutil;
CREATE TABLE UnidadAplicacionEeutil (id int DEFAULT '0' NOT NULL, id_unidad int NOT NULL, id_aplicacion varchar(255) NOT NULL, password varchar(255) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE UnidadOrganica;
CREATE TABLE UnidadOrganica (id int NOT NULL, Codigo_Unidad_Organica varchar(10) NOT NULL, Nombre_Unidad_Organica varchar(255) NOT NULL, Nivel_Administracion tinyint NOT NULL, Entidad_Derecho_Publico varchar(1) NOT NULL, Codigo_Externo varchar(255), Codigo_Unidad_Superior varchar(10) NOT NULL, Nombre_Unidad_Superior varchar(255) NOT NULL, Codigo_Unidad_Raiz varchar(10) NOT NULL, Nombre_Unidad_Raiz varchar(255) NOT NULL, Codigo_Raiz_Derecho_Publico varchar(10), Nombre_Raiz_Derecho_Publico varchar(255), Nivel_Jerarquico tinyint NOT NULL, Estado varchar(1) NOT NULL, Fecha_Alta datetime, Fecha_Baja datetime, Fecha_Anulacion datetime, Fecha_Extincion datetime, created_at datetime NOT NULL, PRIMARY KEY (id), CONSTRAINT unidad_unica_idx UNIQUE (Codigo_Unidad_Organica)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE UnidadUsuario;
CREATE TABLE UnidadUsuario (id int NOT NULL, id_unidad int NOT NULL, id_usuario int NOT NULL, activo tinyint(1) DEFAULT '0' NOT NULL, id_procedimiento int, id_rol int DEFAULT '0' NOT NULL, PRIMARY KEY (id), INDEX fk_UnidadUsuario_UnidadOrganica_idx (id_unidad), INDEX fk_UnidadUsuario_UsuarioInside_idx (id_usuario), INDEX fk_UnidadUsuario_NumeroProcedimiento_idx (id_procedimiento)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE UnidadWsAplicacion;
CREATE TABLE UnidadWsAplicacion (id int NOT NULL, id_unidad int NOT NULL, id_aplicacion int NOT NULL, activo tinyint(1) DEFAULT '0' NOT NULL, id_procedimiento int, PRIMARY KEY (id), INDEX fk_UnidadWsAplicacion_UnidadOrganica_idx (id_unidad), INDEX fk_UnidadWsAplicacion_InsideWsAplicacion_idx (id_aplicacion), INDEX fk_UnidadWsAplicacion_NumeroProcedimiento_idx (id_procedimiento)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE UsuarioGenerador;
CREATE TABLE UsuarioGenerador (id int NOT NULL AUTO_INCREMENT, nif varchar(9) COLLATE utf8_unicode_ci NOT NULL, nombre varchar(255) COLLATE utf8_unicode_ci, apellido1 varchar(255) COLLATE utf8_unicode_ci, apellido2 varchar(255) COLLATE utf8_unicode_ci, telefono varchar(12) COLLATE utf8_unicode_ci, email varchar(255) COLLATE utf8_unicode_ci, sexo enum('H','M') COLLATE utf8_unicode_ci, activo int DEFAULT '1' NOT NULL, PRIMARY KEY (id), CONSTRAINT nif UNIQUE (nif)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE UsuarioInside;
CREATE TABLE UsuarioInside (id int NOT NULL, nif varchar(255) NOT NULL, activo tinyint(1) DEFAULT '1' NOT NULL, fechaCreacion timestamp DEFAULT CURRENT_TIMESTAMP, adminMensaje tinyint(1) DEFAULT '0' NOT NULL, PRIMARY KEY (id), CONSTRAINT nif UNIQUE (nif)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE UsuarioVisor;
CREATE TABLE UsuarioVisor (id int NOT NULL AUTO_INCREMENT, uid varchar(100) NOT NULL COMMENT 'Usuario ldap', nombre varchar(100), apellido1 varchar(100), apellido2 varchar(100), email varchar(255) NOT NULL, telefono varchar(9), activo tinyint DEFAULT '1' NOT NULL COMMENT 'Si el usuario está vigente en la aplicación backend', fecha_creacion timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, fecha_modificacion timestamp DEFAULT '0000-00-00 00:00:00', PRIMARY KEY (id), CONSTRAINT uid UNIQUE (uid)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE AuditoriaRespuestaEnvioJusticia ADD CONSTRAINT fk_AuditoriaRespuestaEnvioJusticia_NumeroProcedimiento FOREIGN KEY (id_procedimiento) REFERENCES NumeroProcedimiento (id) ;
ALTER TABLE AuditoriaRespuestaEnvioJusticia ADD CONSTRAINT fk_AuditoriaRespuestaEnvioJusticia_UnidadOrganica FOREIGN KEY (id_unidad) REFERENCES UnidadOrganica (id);
ALTER TABLE AuditoriaToken ADD CONSTRAINT fk_AuditoriaToken_InsideUsuario FOREIGN KEY (id_token) REFERENCES ExpedienteToken (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE DocumentoInsideFirmas ADD CONSTRAINT FK_DocumentoInsideFirmas_Documento FOREIGN KEY (id_documento) REFERENCES DocumentoInside (id) ;
ALTER TABLE DocumentoInsideFirmas ADD CONSTRAINT FK_DocumentoInsideFirmas_Firma FOREIGN KEY (id_firma) REFERENCES FirmaInside (id);
ALTER TABLE DocumentoInsideMetAdic ADD CONSTRAINT FK_DocumentoInsideMetadatosAdicionales_Documento FOREIGN KEY (id_documento) REFERENCES DocumentoInside (id);
ALTER TABLE DocumentoInsideOrgano ADD CONSTRAINT FK_DocumentoInsideOrgano_Documento FOREIGN KEY (id_documento) REFERENCES DocumentoInside (id);
ALTER TABLE DocumentoUnidad ADD CONSTRAINT fk_DocumentoUnidad_NumeroProcedimiento FOREIGN KEY (id_procedimiento) REFERENCES NumeroProcedimiento (id) ;
ALTER TABLE DocumentoUnidad ADD CONSTRAINT fk_DocumentoUnidad_UnidadOrganica FOREIGN KEY (id_unidad) REFERENCES UnidadOrganica (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE EstructuraCarpetaInside ADD CONSTRAINT FK_ExpInsideIndice_CarInd FOREIGN KEY (id_carpeta_estructura) REFERENCES ExpedienteInsideIndiceCarInd (id);
ALTER TABLE ExpedienteInside ADD CONSTRAINT FK_ExpedienteInside_Indice FOREIGN KEY (id_indice) REFERENCES ExpedienteInsideIndice (id);
ALTER TABLE ExpedienteInsideIndice ADD CONSTRAINT FK_ExpedienteInsideIndice_ExpedienteIndizado FOREIGN KEY (id_expediente_indizado) REFERENCES ExpedienteInsideIndice (id) ;
ALTER TABLE ExpedienteInsideIndice ADD CONSTRAINT FK_ExpedienteInsideIndice_ExpedienteVinculado FOREIGN KEY (id_expediente_vinculado) REFERENCES ExpedienteInside (id);
ALTER TABLE ExpedienteInsideIndiceCarInd ADD CONSTRAINT FK_ExpedienteInsideIndiceCarpetaIndizada_Carpeta FOREIGN KEY (id_carpeta_indizada) REFERENCES ExpedienteInsideIndiceCarInd (id) ;
ALTER TABLE ExpedienteInsideIndiceCarInd ADD CONSTRAINT FK_ExpedienteInsideIndiceCarpetaIndizada_ExpedienteIndizado FOREIGN KEY (id_expediente_indizado) REFERENCES ExpedienteInsideIndice (id);
ALTER TABLE ExpedienteInsideIndiceDocInd ADD CONSTRAINT FK_ExpedienteInsideIndiceDocumentoIndizado_CarpetaIndizada FOREIGN KEY (id_carpeta_indizada) REFERENCES ExpedienteInsideIndiceCarInd (id) ;
ALTER TABLE ExpedienteInsideIndiceDocInd ADD CONSTRAINT FK_ExpedienteInsideIndiceDocumentoIndizado_Indice FOREIGN KEY (id_expediente_indizado) REFERENCES ExpedienteInsideIndice (id);
ALTER TABLE ExpedienteInsideIndiceFirmas ADD CONSTRAINT FK_ExpedienteInsideIndiceFirmas_Expediente FOREIGN KEY (id_expediente) REFERENCES ExpedienteInside (id) ;
ALTER TABLE ExpedienteInsideIndiceFirmas ADD CONSTRAINT FK_ExpedienteInsideIndiceFirmas_Firma FOREIGN KEY (id_firmaInside) REFERENCES FirmaInside (id);
ALTER TABLE ExpedienteInsideInteresado ADD CONSTRAINT FK_ExpedienteInsideInteresado_Expediente FOREIGN KEY (id_expediente) REFERENCES ExpedienteInside (id);
ALTER TABLE ExpedienteInsideMetAdic ADD CONSTRAINT FK_ExpedienteInsideMetadatosAdicionales_Expediente FOREIGN KEY (id_expediente) REFERENCES ExpedienteInside (id);
ALTER TABLE ExpedienteInsideOrgano ADD CONSTRAINT FK_ExpedienteInsideOrgano_Expediente FOREIGN KEY (id_expediente) REFERENCES ExpedienteInside (id);
ALTER TABLE ExpedienteInsideRespuestaEnvioJusticia ADD CONSTRAINT FK_ExpedienteInsideResultadoEnvioJusticia_Expediente FOREIGN KEY (id_expediente_envio) REFERENCES ExpedienteInside (id);
ALTER TABLE ExpedienteToken ADD CONSTRAINT fk_ExpedienteToken_InsideUsuario FOREIGN KEY (id_usuario) REFERENCES UsuarioInside (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE ExpedienteUnidad ADD CONSTRAINT fk_ExpedienteUnidad_NumeroProcedimiento FOREIGN KEY (id_procedimiento) REFERENCES NumeroProcedimiento (id) ;
ALTER TABLE ExpedienteUnidad ADD CONSTRAINT fk_ExpedienteUnidad_UnidadOrganica FOREIGN KEY (id_unidad) REFERENCES UnidadOrganica (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE GeneradorIdInside ADD CONSTRAINT fk_GeneradorIdInside_UnidadOrganica FOREIGN KEY (id_unidad) REFERENCES UnidadOrganica (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE QRTZ_BLOB_TRIGGERS ADD FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP);
ALTER TABLE QRTZ_CRON_TRIGGERS ADD FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP);
ALTER TABLE QRTZ_JOB_LISTENERS ADD FOREIGN KEY (JOB_NAME, JOB_GROUP) REFERENCES QRTZ_JOB_DETAILS (JOB_NAME, JOB_GROUP);
ALTER TABLE QRTZ_SIMPLE_TRIGGERS ADD FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP);
ALTER TABLE QRTZ_TRIGGERS ADD FOREIGN KEY (JOB_NAME, JOB_GROUP) REFERENCES QRTZ_JOB_DETAILS (JOB_NAME, JOB_GROUP);
ALTER TABLE QRTZ_TRIGGER_LISTENERS ADD FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP);
ALTER TABLE UnidadUsuario ADD CONSTRAINT fk_UnidadUsuario_NumeroProcedimiento FOREIGN KEY (id_procedimiento) REFERENCES NumeroProcedimiento (id) ;
ALTER TABLE UnidadUsuario ADD CONSTRAINT fk_UnidadUsuario_UnidadOrganica FOREIGN KEY (id_unidad) REFERENCES UnidadOrganica (id) ;
ALTER TABLE UnidadUsuario ADD CONSTRAINT fk_UnidadUsuario_UsuarioInside FOREIGN KEY (id_usuario) REFERENCES UsuarioInside (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE UnidadWsAplicacion ADD CONSTRAINT fk_UnidadWsAplicacion_InsideWsAplicacion FOREIGN KEY (id_aplicacion) REFERENCES InsideWsAplicacion (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE UnidadWsAplicacion ADD CONSTRAINT fk_UnidadWsAplicacion_NumeroProcedimiento FOREIGN KEY (id_procedimiento) REFERENCES NumeroProcedimiento (id) ;
ALTER TABLE UnidadWsAplicacion ADD CONSTRAINT fk_UnidadWsAplicacion_UnidadOrganica FOREIGN KEY (id_unidad) REFERENCES UnidadOrganica (id);
