/*
 * Copyright (C) 2016 MINHAP, Gobierno de España This program is licensed and may be used, modified
 * and redistributed under the terms of the European Public License (EUPL), either version 1.1 or
 * (at your option) any later version as soon as they are approved by the European Commission.
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package csvstorage.es.gob.aapp.csvstorage.webservices.document.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.0.1 2016-01-14T11:40:48.999+01:00 Generated source
 * version: 3.0.1
 * 
 */
@WebServiceClient(name = "CSVDocumentService",
    wsdlLocation = "http://localhost:8080/csvstorage/services/CSVDocumentService?wsdl",
    targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0")
public class CSVDocumentService_Service extends Service {

  public final static QName SERVICE =
      new QName("urn:es:gob:aapp:csvstorage:webservices:document:v1.0", "CSVDocumentService");
  public final static QName CSVDocumentServicePort =
      new QName("urn:es:gob:aapp:csvstorage:webservices:document:v1.0", "CSVDocumentServicePort");

  public CSVDocumentService_Service(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public CSVDocumentService_Service(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public CSVDocumentService_Service() {
    super(null, SERVICE);
  }

  /**
   *
   * @return returns CSVDocumentService
   */
  @WebEndpoint(name = "CSVDocumentServicePort")
  public CSVDocumentService getCSVDocumentServicePort() {
    return super.getPort(CSVDocumentServicePort, CSVDocumentService.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns CSVDocumentService
   */
  @WebEndpoint(name = "CSVDocumentServicePort")
  public CSVDocumentService getCSVDocumentServicePort(WebServiceFeature... features) {
    return super.getPort(CSVDocumentServicePort, CSVDocumentService.class, features);
  }

}
