/*
 * Copyright (C) 2016 MINHAP, Gobierno de España This program is licensed and may be used, modified
 * and redistributed under the terms of the European Public License (EUPL), either version 1.1 or
 * (at your option) any later version as soon as they are approved by the European Commission.
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */


package csvstorage.es.gob.aapp.csvstorage.webservices.document.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1 2016-01-14T11:40:48.879+01:00 Generated source
 * version: 3.0.1
 */

@WebFault(name = "errorInfo",
    targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0")
public class CSVStorageException extends Exception {

  /**
   * serialVersionUID
   */
  private static final long serialVersionUID = 1L;
  private java.lang.Object errorInfo;

  public CSVStorageException() {
    super();
  }

  public CSVStorageException(String message) {
    super(message);
  }

  public CSVStorageException(String message, Throwable cause) {
    super(message, cause);
  }

  public CSVStorageException(String message, java.lang.Object errorInfo) {
    super(message);
    this.errorInfo = errorInfo;
  }

  public CSVStorageException(String message, java.lang.Object errorInfo, Throwable cause) {
    super(message, cause);
    this.errorInfo = errorInfo;
  }

  public java.lang.Object getFaultInfo() {
    return this.errorInfo;
  }
}
