/*
 * Copyright (C) 2016 MINHAP, Gobierno de España This program is licensed and may be used, modified
 * and redistributed under the terms of the European Public License (EUPL), either version 1.1 or
 * (at your option) any later version as soon as they are approved by the European Commission.
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package csvstorage.es.gob.aapp.csvstorage.webservices.bigaDataTransfer.document.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3 2017-06-13T09:50:54.964+02:00 Generated source
 * version: 3.0.3
 * 
 */
@WebService(targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0",
    name = "CSVDocumentBigDataService")
@XmlSeeAlso({
    csvstorage.es.gob.aapp.csvstorage.webservices.bigaDataTransfer.document.v1.model.ObjectFactory.class,
    ObjectFactory.class})
public interface CSVDocumentBigDataService {

  @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
  @WebResult(name = "guardarDocumentoUuidResponse",
      targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0",
      partName = "parameters")
  @WebMethod(action = "urn:guardarDocumento")
  public csvstorage.es.gob.aapp.csvstorage.webservices.bigaDataTransfer.document.v1.model.GuardarDocumentoUuidResponse guardarDocumento(
      @WebParam(partName = "parameters", name = "guardarDocumento",
          targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0") GuardarDocumento parameters)
      throws CSVStorageException;

  @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
  @WebResult(name = "obtenerDocumentoResponse",
      targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0",
      partName = "parameters")
  @WebMethod(action = "urn:obtenerDocumento")
  public csvstorage.es.gob.aapp.csvstorage.webservices.bigaDataTransfer.document.v1.model.ObtenerDocumentoBigDataResponse obtenerDocumento(
      @WebParam(partName = "parameters", name = "obtenerDocumento",
          targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0") ObtenerDocumento parameters)
      throws CSVStorageException;

  @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
  @WebResult(name = "modificarDocumentoResponse",
      targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0",
      partName = "parameters")
  @WebMethod(action = "urn:modificarDocumento")
  public csvstorage.es.gob.aapp.csvstorage.webservices.bigaDataTransfer.document.v1.model.GuardarDocumentoResponse modificarDocumento(
      @WebParam(partName = "parameters", name = "modificarDocumento",
          targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0") ModificarDocumento parameters)
      throws CSVStorageException;

  @WebResult(name = "obtenerHashDocumentoResponse", targetNamespace = "")
  @RequestWrapper(localName = "obtenerHashDocumento",
      targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0",
      className = "csvstorage.es.gob.aapp.csvstorage.webservices.bigaDataTransfer.document.v1.ObtenerHashDocumento")
  @WebMethod(action = "urn:obtenerHashDocumento")
  @ResponseWrapper(localName = "obtenerHashDocumentoResponse",
      targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0",
      className = "csvstorage.es.gob.aapp.csvstorage.webservices.bigaDataTransfer.document.v1.ObtenerHashDocumentoResponse")
  public java.lang.String obtenerHashDocumento(@WebParam(name = "credential",
      targetNamespace = "") csvstorage.es.gob.aapp.csvstorage.webservices.bigaDataTransfer.document.v1.model.WSCredential credential,
      @WebParam(name = "uuid", targetNamespace = "") java.lang.String uuid,
      @WebParam(name = "algoritmo", targetNamespace = "") java.lang.String algoritmo)
      throws CSVStorageException;

  @WebResult(name = "documentoTamanioResponse", targetNamespace = "")
  @RequestWrapper(localName = "obtenerTamanioDocumento",
      targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0",
      className = "csvstorage.es.gob.aapp.csvstorage.webservices.bigaDataTransfer.document.v1.ObtenerTamanioDocumento")
  @WebMethod(action = "urn:obtenerTamanioDocumento")
  @ResponseWrapper(localName = "obtenerTamanioDocumentoResponse",
      targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0",
      className = "csvstorage.es.gob.aapp.csvstorage.webservices.bigaDataTransfer.document.v1.ObtenerTamanioDocumentoResponse")
  public java.lang.Long obtenerTamanioDocumento(@WebParam(name = "credential",
      targetNamespace = "") csvstorage.es.gob.aapp.csvstorage.webservices.bigaDataTransfer.document.v1.model.WSCredential credential,
      @WebParam(name = "uuid", targetNamespace = "") java.lang.String uuid)
      throws CSVStorageException;

  @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
  @WebResult(name = "obtenerInfoContenidoResponse",
      targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:model:v1.0",
      partName = "parameters")
  @WebMethod(action = "urn:obtenerInfoContenido")
  public csvstorage.es.gob.aapp.csvstorage.webservices.bigaDataTransfer.document.v1.model.ObtenerInfoContenidoResponse obtenerInfoContenido(
      @WebParam(partName = "parameters", name = "obtenerInfoContenido",
          targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0") ObtenerInfoContenido parameters)
      throws CSVStorageException;
}
