/*
 * Copyright (C) 2016 MINHAP, Gobierno de España This program is licensed and may be used, modified
 * and redistributed under the terms of the European Public License (EUPL), either version 1.1 or
 * (at your option) any later version as soon as they are approved by the European Commission.
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package csvstorage.es.gob.aapp.csvstorage.webservices.bigaDataTransfer.document.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.3 2017-06-13T09:50:55.011+02:00 Generated source
 * version: 3.0.3
 * 
 */
@WebServiceClient(name = "CSVDocumentBigDataService",
    wsdlLocation = "http://des-csvstorage.redsara.es/csvstorage/services/CSVDocumentBigDataService?wsdl",
    targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:document:v1.0")
public class CSVDocumentBigDataService_Service extends Service {

  public final static URL WSDL_LOCATION;

  public final static QName SERVICE = new QName(
      "urn:es:gob:aapp:csvstorage:webservices:document:v1.0", "CSVDocumentBigDataService");
  public final static QName CSVDocumentBigDataServicePort = new QName(
      "urn:es:gob:aapp:csvstorage:webservices:document:v1.0", "CSVDocumentBigDataServicePort");
  static {
    URL url = null;
    try {
      url = new URL(
          "http://des-csvstorage.redsara.es/csvstorage/services/CSVDocumentBigDataService?wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(CSVDocumentBigDataService_Service.class.getName()).log(
          java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
          "http://des-csvstorage.redsara.es/csvstorage/services/CSVDocumentBigDataService?wsdl");
    }
    WSDL_LOCATION = url;
  }

  public CSVDocumentBigDataService_Service(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public CSVDocumentBigDataService_Service(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public CSVDocumentBigDataService_Service() {
    super(WSDL_LOCATION, SERVICE);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public CSVDocumentBigDataService_Service(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public CSVDocumentBigDataService_Service(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public CSVDocumentBigDataService_Service(URL wsdlLocation, QName serviceName,
      WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   *
   * @return returns CSVDocumentBigDataService
   */
  @WebEndpoint(name = "CSVDocumentBigDataServicePort")
  public CSVDocumentBigDataService getCSVDocumentBigDataServicePort() {
    return super.getPort(CSVDocumentBigDataServicePort, CSVDocumentBigDataService.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns CSVDocumentBigDataService
   */
  @WebEndpoint(name = "CSVDocumentBigDataServicePort")
  public CSVDocumentBigDataService getCSVDocumentBigDataServicePort(WebServiceFeature... features) {
    return super.getPort(CSVDocumentBigDataServicePort, CSVDocumentBigDataService.class, features);
  }

}
