/*
 * Copyright (C) 2016 MINHAP, Gobierno de España This program is licensed and may be used, modified
 * and redistributed under the terms of the European Public License (EUPL), either version 1.1 or
 * (at your option) any later version as soon as they are approved by the European Commission.
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package csvstorage.es.gob.aapp.csvstorage.webservices.documentmtom.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.0.1 2016-01-14T11:39:44.192+01:00 Generated source
 * version: 3.0.1
 * 
 */
@WebServiceClient(name = "CSVDocumentMtomService",
    wsdlLocation = "http://localhost:8080/csvstorage/services/CSVDocumentMtomService?wsdl",
    targetNamespace = "urn:es:gob:aapp:csvstorage:webservices:documentmtom:v1.0")
public class CSVDocumentMtomService_Service extends Service {

  public final static QName SERVICE = new QName(
      "urn:es:gob:aapp:csvstorage:webservices:documentmtom:v1.0", "CSVDocumentMtomService");
  public final static QName CSVDocumentMtomServicePort = new QName(
      "urn:es:gob:aapp:csvstorage:webservices:documentmtom:v1.0", "CSVDocumentMtomServicePort");


  public CSVDocumentMtomService_Service(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public CSVDocumentMtomService_Service(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public CSVDocumentMtomService_Service() {
    super(null, SERVICE);
  }


  /**
   *
   * @return returns CSVDocumentMtomService
   */
  @WebEndpoint(name = "CSVDocumentMtomServicePort")
  public CSVDocumentMtomService getCSVDocumentMtomServicePort() {
    return super.getPort(CSVDocumentMtomServicePort, CSVDocumentMtomService.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns CSVDocumentMtomService
   */
  @WebEndpoint(name = "CSVDocumentMtomServicePort")
  public CSVDocumentMtomService getCSVDocumentMtomServicePort(WebServiceFeature... features) {
    return super.getPort(CSVDocumentMtomServicePort, CSVDocumentMtomService.class, features);
  }

}
