/*
 * Copyright (C) 2016 MINHAP, Gobierno de España This program is licensed and may be used, modified
 * and redistributed under the terms of the European Public License (EUPL), either version 1.1 or
 * (at your option) any later version as soon as they are approved by the European Commission.
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package es.mpt.dsic.eeutil.client.operFirma.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.3 2016-02-25T12:52:24.707+01:00 Generated source
 * version: 3.0.3
 * 
 */
@WebServiceClient(name = "EeUtilServiceMtomImplService",
    wsdlLocation = "http://10.1.74.212:8090/eeutil-oper-firma/ws/EeUtilServiceMtom?wsdl",
    targetNamespace = "http://impl.service.ws.inside.dsic.mpt.es/")
public class EeUtilServiceMtomImplService extends Service {



  public final static QName SERVICE =
      new QName("http://impl.service.ws.inside.dsic.mpt.es/", "EeUtilServiceMtomImplService");
  public final static QName EeUtilServiceMtomImplPort =
      new QName("http://impl.service.ws.inside.dsic.mpt.es/", "EeUtilServiceMtomImplPort");


  public EeUtilServiceMtomImplService(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public EeUtilServiceMtomImplService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public EeUtilServiceMtomImplService() {
    super(null, SERVICE);
  }

  /**
   *
   * @return returns EeUtilServiceMtom
   */
  @WebEndpoint(name = "EeUtilServiceMtomImplPort")
  public EeUtilServiceMtom getEeUtilServiceMtomImplPort() {
    return super.getPort(EeUtilServiceMtomImplPort, EeUtilServiceMtom.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns EeUtilServiceMtom
   */
  @WebEndpoint(name = "EeUtilServiceMtomImplPort")
  public EeUtilServiceMtom getEeUtilServiceMtomImplPort(WebServiceFeature... features) {
    return super.getPort(EeUtilServiceMtomImplPort, EeUtilServiceMtom.class, features);
  }

}
