/*
 * Copyright (C) 2016 MINHAP, Gobierno de España This program is licensed and may be used, modified
 * and redistributed under the terms of the European Public License (EUPL), either version 1.1 or
 * (at your option) any later version as soon as they are approved by the European Commission.
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and more details. You
 * should have received a copy of the EUPL1.1 license along with this program; if not, you may find
 * it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package es.mpt.dsic.eeutil.client.operFirma.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3 2016-02-25T12:52:24.707+01:00 Generated source
 * version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://service.ws.inside.dsic.mpt.es/", name = "EeUtilServiceMtom")
@XmlSeeAlso({ObjectFactory.class})
public interface EeUtilServiceMtom {

  @WebResult(name = "ResultadoValidacionInfo", targetNamespace = "")
  @RequestWrapper(localName = "validacionFirma",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.eeutil.client.operFirma.model.ValidacionFirma")
  @WebMethod(action = "urn:validacionFirma")
  @ResponseWrapper(localName = "validacionFirmaResponse",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.eeutil.client.operFirma.model.ValidacionFirmaResponse")
  public es.mpt.dsic.eeutil.client.operFirma.model.ResultadoValidacionInfo validacionFirma(
      @WebParam(name = "aplicacionInfo",
          targetNamespace = "") es.mpt.dsic.eeutil.client.operFirma.model.ApplicationLogin aplicacionInfo,
      @WebParam(name = "Firma", targetNamespace = "") javax.activation.DataHandler firma,
      @WebParam(name = "TipoFirma", targetNamespace = "") java.lang.String tipoFirma,
      @WebParam(name = "DatosFirmadosMtom",
          targetNamespace = "") es.mpt.dsic.eeutil.client.operFirma.model.DatosFirmadosMtom datosFirmadosMtom)
      throws InSideException;

  @WebResult(name = "FirmaProcesada", targetNamespace = "")
  @RequestWrapper(localName = "postProcesarFirma",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.eeutil.client.operFirma.model.PostProcesarFirma")
  @WebMethod(action = "urn:postProcesarFirma")
  @ResponseWrapper(localName = "postProcesarFirmaResponse",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.eeutil.client.operFirma.model.PostProcesarFirmaResponse")
  public byte[] postProcesarFirma(@WebParam(name = "aplicacionInfo",
      targetNamespace = "") es.mpt.dsic.eeutil.client.operFirma.model.ApplicationLogin aplicacionInfo,
      @WebParam(name = "FirmaMtom", targetNamespace = "") javax.activation.DataHandler firmaMtom)
      throws InSideException;

  @WebResult(name = "resultadoObtenerInformacionFirma", targetNamespace = "")
  @RequestWrapper(localName = "obtenerInformacionFirma",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.eeutil.client.operFirma.model.ObtenerInformacionFirma")
  @WebMethod(action = "urn:obtenerInformacionFirma")
  @ResponseWrapper(localName = "obtenerInformacionFirmaResponse",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.eeutil.client.operFirma.model.ObtenerInformacionFirmaResponse")
  public es.mpt.dsic.eeutil.client.operFirma.model.InformacionFirma obtenerInformacionFirma(
      @WebParam(name = "aplicacionInfo",
          targetNamespace = "") es.mpt.dsic.eeutil.client.operFirma.model.ApplicationLogin aplicacionInfo,
      @WebParam(name = "Firma", targetNamespace = "") javax.activation.DataHandler firma,
      @WebParam(name = "opcionesObtenerInformacionFirma",
          targetNamespace = "") es.mpt.dsic.eeutil.client.operFirma.model.OpcionesObtenerInformacionFirma opcionesObtenerInformacionFirma,
      @WebParam(name = "ContenidoMtom",
          targetNamespace = "") javax.activation.DataHandler contenidoMtom)
      throws InSideException;

  @WebResult(name = "resultadoValidarCertificado", targetNamespace = "")
  @RequestWrapper(localName = "validarCertificado",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.eeutil.client.operFirma.model.ValidarCertificado")
  @WebMethod(action = "urn:validarCertificado")
  @ResponseWrapper(localName = "validarCertificadoResponse",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.eeutil.client.operFirma.model.ValidarCertificadoResponse")
  public es.mpt.dsic.eeutil.client.operFirma.model.ResultadoValidarCertificado validarCertificado(
      @WebParam(name = "aplicacionInfo",
          targetNamespace = "") es.mpt.dsic.eeutil.client.operFirma.model.ApplicationLogin aplicacionInfo,
      @WebParam(name = "certificate", targetNamespace = "") java.lang.String certificate)
      throws InSideException;

  @WebResult(name = "resultadoAmpliarFirmaMtom", targetNamespace = "")
  @RequestWrapper(localName = "ampliarFirma",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.eeutil.client.operFirma.model.AmpliarFirma")
  @WebMethod(action = "urn:ampliarFirma")
  @ResponseWrapper(localName = "ampliarFirmaResponse",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.eeutil.client.operFirma.model.AmpliarFirmaResponse")
  public es.mpt.dsic.eeutil.client.operFirma.model.ResultadoAmpliarFirmaMtom ampliarFirma(@WebParam(
      name = "aplicacionInfo",
      targetNamespace = "") es.mpt.dsic.eeutil.client.operFirma.model.ApplicationLogin aplicacionInfo,
      @WebParam(name = "FirmaMtom", targetNamespace = "") javax.activation.DataHandler firmaMtom,
      @WebParam(name = "configuracionAmpliarFirma",
          targetNamespace = "") es.mpt.dsic.eeutil.client.operFirma.model.ConfiguracionAmpliarFirma configuracionAmpliarFirma)
      throws InSideException;

  @WebResult(name = "ListaFirmantes", targetNamespace = "")
  @RequestWrapper(localName = "obtenerFirmantes",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.eeutil.client.operFirma.model.ObtenerFirmantes")
  @WebMethod(action = "urn:obtenerFirmantes")
  @ResponseWrapper(localName = "obtenerFirmantesResponse",
      targetNamespace = "http://service.ws.inside.dsic.mpt.es/",
      className = "es.mpt.dsic.eeutil.client.operFirma.model.ObtenerFirmantesResponse")
  public es.mpt.dsic.eeutil.client.operFirma.model.ListaFirmaInfo obtenerFirmantes(@WebParam(
      name = "aplicacionInfo",
      targetNamespace = "") es.mpt.dsic.eeutil.client.operFirma.model.ApplicationLogin aplicacionInfo,
      @WebParam(name = "FirmaMtom", targetNamespace = "") javax.activation.DataHandler firmaMtom,
      @WebParam(name = "TipoFirma", targetNamespace = "") java.lang.String tipoFirma)
      throws InSideException;
}
